colinhacks/zod

- README.md
Below the Zod example the line reads "This more declarative API makes schema definitions vastly more concise.", having the comment spread out as it was made the io-ts example look larger.
I feel this makes it more fair and about the code. I am in no way affiliated with io-ts just happen to be a passer by.
> Allow fair comparison between io-ts and Zod

- README.md
It looks like this ``j`` wasn't intended to be in the doc.
> Remove erroneous character from readme

- README.md
The current one has an invalid key name: `confirm vs confirmPassword` mismatch typo.
> Fix confirm example in README.md

- src/__tests__/all-errors.test.ts
It seems that some errors are omitted when reusing schema instance. Adding a simple test.
> Test that all errors are collected even if schema instance is reused.

- README.md
- src/__tests__/transformer.test.ts
- src/types/base.ts
**Before this change**:
```ts
const schema = z.object({
sandbox: z.boolean().default(true)
});
// Good - returns { sandbox: true } - which makes sense as it's not supplied
schema.parse({}); 
// Bad! - returns { sandbox: true } even though I've provided a  value for it.
schema.parse({ sandbox: false }); 
```
**After this change**:
```ts
const schema = z.object({
sandbox: z.boolean().default(true)
});
// Good - returns { sandbox: true } - which makes sense as it's not supplied
schema.parse({}); 
// Good - returns { sandbox: false } as a value was supplied to the sandbox property
schema.parse({ sandbox: false }); 
```
As I'm using the null coalescing operator it means either `null` or `undefined` values will cause the default value to be used.
We might want to limit this only to `undefined` …
> Use .default() value only when schema is null or undefined

- README.md
- src/PseudoPromise.ts
- src/__tests__/async-parsing.test.ts
- src/__tests__/object.test.ts
- src/__tests__/transformer.test.ts
- src/parser.ts
- src/playground.ts
- src/types/base.ts
- yarn.lock
This PR fixes the async multi-error accumulation bug (#179) by adding a `catch` method to the `PseudoPromise` class and using it in while parsing object schemas.
> fix: add PseudoPromise catch for use in ZodType.object validation

- package.json
@vriad Not sure why this was changed in first place - perhaps it was an accident, as I'm unfamiliar with this syntax.
> fix: update path to main file in package.json. Fixes #192

- src/parser.ts
In the context of issue #205, this change makes parsing 4x faster in my tests.
> delay costly makeError to when it is needed

- package.json
- yarn.lock
Adds [Husky](https://github.com/typicode/husky) & [lint-staged](https://github.com/okonet/lint-staged) as new dev dependencies. This addition will initially start formatting each staged file coming in. Once each file is formatted, though, upcoming PRs should be focused on the content without the unnecessary bloat of formatting unformatted code.
Relates to #225.
> Add husky & lint-staged

- package.json
- tsconfig.base.json
Excludes tests & playground from the published package. Also, use `/lib` instead of `lib` in `files` of `package.json` based on feedback in [this comment](https://github.com/colinhacks/zod/issues/225#issuecomment-739468062).
Relates to #225.
> Reduce package size

- README.md
👋  howdy, sorry for the drive-by edits. Updating the readme to match the current reality. I removed the note about `required()` since it was sort of misleading and i couldn't think of another way to explain the situation without adding a bunch of yup specific details you probably don't want in your readme. tl;dr;
`required()` is weird, and named poorly, it generally means "not null or undefined" except in the string case where it also means "not an empty string" (the empty array case has been finally changed to be normal and not mean "no empty arrays"). In terms of feature comparison tho, it's not the right method to call out. Yup has a "not undefined" method, it's called `defined()` which is the more apples to apples comparison to zod's `required()`. IDK if that's worth noting to your …
> Update yup differences

- .github/workflows/fix.yaml
- .github/workflows/test.yaml
The just-released [Deno 1.7.1](https://github.com/denoland/deno/releases/tag/v1.7.1) fixes the last issue (https://github.com/denoland/deno/issues/9097) that was causing invalid bundles to be generated for Zod. This PR adds a sanity check that the generated bundle is at least importable without an error, and updates the test matrix to run against Deno 1.7.1 and the latest stable Deno 1.x release (please feel free to change that if you'd prefer to only run one or the other), dropping the test for the broken-bundling Deno 1.6.
Also adds` yarn clean` to fix.yaml to remove stale files, and removes the previously accidentally-committed stale `bundle.js`.
I am optimistic that this will remain stable from now on, but if it does break don't hesitate to tag me. 🙃
> test(deno bundle): add syntax sanity check for deno bundle v1.7.1+

- package.json
It seems like perhaps this was just a mistake of omitting the -D because can't seem to find any reference to using the plugin in the main source.
> Moves eslint-plugin-unused-imports to dev deps

- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/__tests__/string.test.ts
- src/types.ts
Previously the regex was missing anchors (^ and $) so validation would pass as long as the argument contained a valid UUID as a substring. Closes #389.
> Fixed UUID regex

- src/ZodError.ts
Currently, the ZodError message looks buggy when `err.path` is empty. There should be some kind of explicit indication of an error occurring at the root-level value, instead of just showing an empty string.
Before:
```
Issue #1: unrecognized_keys at
```
After:
```
Issue #1: unrecognized_keys at [[root]]
```
> Improve error message when err.path is empty

- src/types.ts
This commit broke UUID support for versions other than 4: https://github.com/colinhacks/zod/commit/e0f7412358a66efa25ffc0374d7945e0e3111b05
This PR adds support for all UUID versions again. Additionally, it supports both case-insensitive and case-sensitive UUIDs (using the `i` flag).
Fixes #415
> Add support for all UUID versions, fix #415

- deno/lib/PseudoPromise.ts
- deno/lib/helpers/util.ts
- src/PseudoPromise.ts
- src/helpers/util.ts
We faced with issue, that in old browsers Symbol is not supported.
As I see, in the code, Symbol is used as unique value (not as unique key in an object).
So I added the check if Symbol exists and use an Object if not.
> Fix "Symbol is undefined" error

- src/types.ts
This means that docstrings on the schema definition will transfer to the z.Infer generated type.
Fixes #423 
I can't think of a way to embed this into a test though. If anyone has any idea how to do so I'm all ears.
> make addQuestionMarks a homomorphic mapped type

- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/__tests__/string.test.ts
- src/types.ts
The nil UUID (`00000000-0000-0000-0000-000000000000`) is a valid UUID according to [RFC4122 (Section 4.1.7)](https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.7). This PR adds it to the regex for UUID validation. It is added separately to avoid allowing `0` in locations where it is not permitted for other UUID versions.
> Fix not considering the nil UUID a valid UUID

- README.md
Updated to be consistent with the comment above, which says that  `.nonempty` is deprecated .
Related issue: https://github.com/colinhacks/zod/issues/439
> Fix README.md recommending deprecated method

- deno/lib/types.ts
- src/types.ts
In my team's codebase, we have used `.nonstrict()` in many, many places because it was necessary with zod 1. Easy example: validating `process.env`, which always has extra properties that we don't care about.  Now that we've updated to zod 3, our code is still working, but it's unnecessary and slightly less safe than the default behaviour of `.strip()`. It'd be good if our IDE/linter could help us find these cases _and_ make sure that people who haven't carefully read zod changelogs don't add any new usages of `.nonstrict()`.
> Deprecate `.nonstrict()`

- CHANGELOG.md
- deno/lib/__tests__/object.test.ts
- deno/lib/types.ts
- src/__tests__/object.test.ts
- src/types.ts
Addresses https://github.com/pkvince/medzy-monorepo/pull/295
This is a breaking change so let's wait until @colinhacks checks in
> Stop inferring `unknown` fields as optional

- deno/lib/benchmarks/index.ts
- deno/lib/benchmarks/object.ts
- deno/lib/benchmarks/string.ts
- package.json
- src/benchmarks/index.ts
- src/benchmarks/object.ts
- src/benchmarks/string.ts
- yarn.lock
As part of the work to help improve zod's performance, it seems to me like the first step is to add some benchmarking to track performance as we make changes. What's measured improves and all that.
Added a few really basic benchmarks and will want to expand this before landing it, but wanted to get some early feedback on this approach from @colinhacks and the rest of the community. It's also possible that we want these benchmarks to live "outside" of the code, so that it can import multiple versions to track changes, benchmark other similar libraries, incorporate other tools, etc.
TODO:
===
```
z.string: empty string x 39,259 ops/sec ±3.98% (77 runs sampled)
z.string: short string x 40,917 ops/sec ±2.43% (77 runs sampled)
z.string: long string x 40,562 ops/sec ±2.54% (84 runs sampled) …
```
> Add benchmarking for parser

- src/types.ts
Fix getter on ZodString for maxLength, changing the def.checks from kind min to max
> Fix getter for maxLength

- deno/lib/__tests__/parseUtil.test.ts
- deno/lib/helpers/parseUtil.ts
- src/__tests__/parseUtil.test.ts
- src/helpers/parseUtil.ts
`===` comparisons only works when Zod is installed once in a monorepo setup with multiple packages using Zod.
This PR changes it to use structural type checking rather than referential equality checking.
The test reproduces the issue (i.e. fails before applying the change).
Closes #556
> Fix isInvalid equality check

- CHANGELOG.md
- README.md
- deno/lib/__tests__/void.test.ts
- deno/lib/types.ts
- src/__tests__/void.test.ts
- src/types.ts
`z.void()` previously accepted `null` or `undefined`, but the TypeScript `void` type is only assignable from `undefined` (unless `strictNullChecks` is `false`, in which case every type is assignable from `null` regardless).
This unsoundness could be observed as follows:
```js
const x = z.string().or(z.void()).parse(null);
if (x !== undefined) {
// TypeScript infers x is a string, but it’s actually null
x.trim(); // oops
}
```
> Fix z.void() to reject null

- README.md
Add `typeof` to input/output/infer example.
> Docs: Add typeof to input/output/infer example

- src/types.ts
This is my attempt to add the type alias as described by Colin [here](https://github.com/colinhacks/zod/issues/540#issuecomment-883043680).
---
<details>
<summary>Examples of usage with the following schema</summary>
```ts
import {z} from 'zod';
// Current date state:
const currentMonth = new Date().getUTCMonth() + 1
const currentYear  = new Date().getUTCFullYear() - 2000
// Custom Validations:
// `.refine(inRange(x,y), err)` is like `z.number().min(x, err).max(y, err)`, but works after `transform()`
const inRange    = (x: number, y: number) => (n: number) => (n >= x && n <= y)
const r_isDigits = /^[0-9]+$/
// Custom Errors:
const errorRangeMonth = "Must be a number between 1 and 12"
const errorMinYear    = "Value should not be in the past"
const errorRangeCSC   = "Value should be 3 …
```
> chore: Export a `SuperRefinement<T>` alias

- package.json
When using Zod in a react-native app, we see the following warning when running the bundler:
```
warn Package zod has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in <path>/node_modules/zod/package.json
```
The problem is described in https://github.com/react-native-community/cli/issues/1168 and that is where it should be properly fixed. In the meantime (that issue has been open for some time), the warning can be fixed in affected packages by adding an export for `package.json`.
> Fix react-native/metro bundler warning

- deno/lib/types.ts
- src/types.ts
Before:
```
$ deno cache https://deno.land/x/zod@v3.8.0/mod.ts
Check https://deno.land/x/zod@v3.8.0/mod.ts
error: TS2564 [ERROR]: Property 'is' has no initializer and is not definitely assigned in the constructor.
is: never;
~~
at https://deno.land/x/zod@v3.8.0/types.ts:156:3
TS2564 [ERROR]: Property 'check' has no initializer and is not definitely assigned in the constructor.
check: never;
~~~~~
at https://deno.land/x/zod@v3.8.0/types.ts:159:3
Found 2 errors.
```
Why is https://deno.land/x/zod 2 patch releases behind npm?
> Fix for TypeScript 4.4

- README.md
Add documentation for `ZodArray.element` (fixes #744), using the same format as the documentation for `ZodObject.shape`.
> Fix documentation for ZodArray .element (issue #744)

- README.md
I believe the intention was to use `z.number()` instead of `z.string()`
> Fix typing typo in documentation

- README.md
The Twitter link was using Markdown inside of HTML and thus was broken because it's being centered in a `<p>` tag. I changed it to just a regular ol' `<a>` tag.
> Fix broken twitter link

- src/types.ts
Addresses issues where `as const` needs to be used in definitions to allow further type inference.
Currently `as const` values are prevented from being used since the existing signature requires writeable arrays and tuples 
Using `as const` to declare actual readonly tuples instead of populating writeable arrays enables strong type inference and ensures arity is detectable for calls to union constructors (which need a tuple of at least 2 members).
Fixes https://github.com/colinhacks/zod/issues/831
> Add Readonly to ZodUnionOptions

- deno/lib/ZodError.ts
- deno/lib/__tests__/error.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/error.test.ts
- src/types.ts
See #461 
Also the error produced by `ZodLiteral` did not actually match the `ZodInvalidTypeIssue` interface or `ERROR_HANDLING.md` documentation (`expected` and `received` were not actually `ZodParsedType`s)
> Don't include received value in enum/literal error messages (fixes #461)

- README.md
Almost the same block on custom error messages can be found in lines 336–345.
```js
const name = z.string({
required_error: "Name is required",
invalid_type_error: "Name must be a string",
});
```
Leaves the question whether the properties in that object can be both => 
`required`/`required_error` and `invalid`/`invalid_type_error`
> Remove duplicated block on custom error messages

- ERROR_HANDLING.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/all-errors.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/all-errors.test.ts
- src/types.ts
- Adds two types `z.inferFlattenedErrors` and alias type `z.inferFormErrors` to [infer error result types for `flatten()` from a schema](https://github.com/colinhacks/zod/pull/856/files#diff-ae3ae59764197d1e97d44cb8d123d849b078e60d66aa6d8332851e7b51fb24abR377).
- Adds additional overloading for `flatten` to [support type-safety with the new types](https://github.com/colinhacks/zod/pull/856/files#diff-ae3ae59764197d1e97d44cb8d123d849b078e60d66aa6d8332851e7b51fb24abR413-R417).
Fixes #855
> Add types to extract error results from schema

- README.md
I added graphql-codegen-typescript-validation-schema in README.md
see: https://github.com/Code-Hex/graphql-codegen-typescript-validation-schema
> added graphql-codegen-typescript-validation-schema (README.md) 

- deno/lib/types.ts
- src/types.ts
I think that zod should export `ZodDiscriminatedUnionOption`. Please let me know if there is a good reason not to do this.
> exporting ZodDiscriminatedUnionOption

- CODE_OF_CONDUCT.md
As the community continues to grow and more people are involved in both contributing code, reviewing PRs, and address issues and questions, I believe we should establish a Code of Conduct to foster a healthy community. I've chosen a very popular one used in many open source projects big and small: [The Contributor's Covenant](https://www.contributor-covenant.org) but I'm open to others.
Additionally, I would like to grow the (very lonely) [Discord server](https://discord.gg/EuFJWgP2TG) I started for Zod a while back, but want there to be a consistent set of rules around interaction there and here.
> Add Contributor's Convenant as Code of Conduct

- deno/lib/benchmarks/index.ts
- deno/lib/benchmarks/realworld.ts
- src/benchmarks/index.ts
- src/benchmarks/realworld.ts
This PR exists to complement / gut-check the work in #1023 - the `typeCache` would make the realworld benchmark faster if it was a net win, because it would replace some `typeof` checks with a map lookup. This benchmark confirms that removing typeCache is about 10% faster in my testing, even if there are repeated values in the dataset.
> Add realworld benchmark

- docs/screencasts.md
Removed Doc against issue #1010
**ISSUE**: Unnecessary Documentation in zod/docs. Documentation ( [screencasts.md](https://github.com/colinhacks/zod/blob/master/docs/screencasts.md)) contains random strings making no sense of its purpose.
**PROPOSED**: Removal of screencasts.md documentation from the repository.
> Removed screencasts.md

- docs/_navbar.md
Removed Doc against issue #1009
**ISSUE**: Unnecessary Documentation in zod/docs. All links inside the documentation ( [_navbar.md](https://github.com/colinhacks/zod/blob/master/docs/_navbar.md)) have expired or lead to 404 not found page leaving it useless and occupy free space.
**PROPOSED**: Removal of _navbar.md documentation from the repository.
> Removed _navbar.md

- docs/_coverpage.md
- docs/_navbar.md
Removed Doc against issue [#1008](https://github.com/colinhacks/zod/issues/1008)
**ISSUE**: Unnecessary Documentation in zod/docs. All links inside the documentation ( [_coverpage.md](https://github.com/colinhacks/zod/blob/master/docs/_coverpage.md)) have expired or lead to 404 not found page leaving it useless and occupy free space.
**PROPOSED**: Removal of _coverpage.md documentation from the repository.
> Removed _coverpage.md

- deno/lib/__tests__/firstparty.test.ts
- deno/lib/types.ts
- src/__tests__/firstparty.test.ts
- src/types.ts
Is there a reason why `ZodDiscriminatedUnion`, which is a `ZodFirstPartyTypeKind`, isn't in the `ZodFirstPartySchemaTypes` union type? It seems like an oversight?
> Add ZodDiscriminatedUnion to ZodFirstPartySchemaTypes

- README.md
- tsconfig.base.json
So the current setup is that `zod` has a compile target of es5, which applies to both its ES Module and CJS distributions. Zod's internals use quite a lot of modern features. TypeScript is polyfilling all of those features in the distributed code. TypeScript's polyfills are very good and probably as fast as they can be, but they're not as fast as the native code. For example, every array or object spread and every generator gets compiled to something with a bit more indirection.
That indirection looks like it's costing a real slowdown for some Zod functions.
So, bumping the target to ES2018 would cost IE11 support if it was done uniformly. Assuming that IE11 support is still critical (that's for the maintainers to decide, not me), a possibility might be targeting es2018 in the module …
> Performance - target es2018

- src/types.ts
Okay! Got another. Paths, specifically the pattern `[...ctx.path, key]` is a performance hotspot. This PR replaces that pattern with an object, `ParseInputLazyPath`, which is `ParseInput`, but instead of concatenating the path immediately, only creates the new array if it's needed (if there is an error). This yields a 20-30% performance boost on inputs like the realworld benchmark and the object benchmarks, and I can't easily profile it, but should reduce memory overhead a bit too.
- Refs #205
---
Before
```
% y benchmark
yarn run v1.22.4
$ ts-node src/benchmarks/index.ts
realworld: valid x 3,819 ops/sec ±0.97% (92 runs sampled)
z.enum: valid x 12,049,817 ops/sec ±0.72% (87 runs sampled)
z.enum: invalid x 65,717 ops/sec ±4.31% (88 runs sampled)
z.undefined: valid x 10,393,122 ops/sec …
```
> Faster paths for nested parsers

- deno/lib/types.ts
- src/types.ts
This increases object parsing performance by about 8-10% by skipping a call to Object.keys and instead using `in`. I know it's odd, but this seemingly insignificant few lines of code really seems to be a hotspot.
Benchmark results: https://observablehq.com/d/8978a77c49a9c6ef - there's a lot of test jitter in mainly unrelated benchmarks - no reason to think this'll change string parsing performance.
> Faster extra keys detection

- deno/lib/types.ts
- src/types.ts
Apologies for not opening an issue first but this felt like low hanging fruit :)
It seems like there was some testing done on the repo's husky hooks (https://github.com/colinhacks/zod/commit/0dbd4ec8154d3390e23bdd2b1238fd20276893bf) and these no-op string expressions were accidentally pushed.
> Remove hanging string expressions

- README.md
- README_ZH.md
I was using this great recommendation for JSON type and saw this small improvement to reduce duplication.
> docs: infer `Literal` from the schema in JSON type example

- README.md
Adding the [zod-to-openapi](https://github.com/asteasolutions/zod-to-openapi) library to the ecosystem links.
Relevant dicsussion: https://github.com/colinhacks/zod/discussions/1107
> Add zod-to-openapi to Ecosystem in the Readme

- ERROR_HANDLING.md
Noticed a typo while reading the error handling guide.
> docs: fix typo on the error handling guide

- .gitignore
- deno/lib/__tests__/transformer.test.ts
- deno/lib/types.ts
- src/__tests__/transformer.test.ts
- src/types.ts
Closes out part of #696 . Except only on transforms!
```
z
.string()
.transform((data, ctx) => {
const i = strs.indexOf(data)
if (i === -1) {
ctx.addIssue({
code: 'custom',
message: `${data} is not one of our allowed strings`,
})
}
return data.length
})
.parse("asdf");
```
Will throw. `ctx` works just like in superRefine()
> feat: allow ctx.addIssue from transform

- README.md
- deno/lib/__tests__/transformer.test.ts
- deno/lib/types.ts
- src/__tests__/transformer.test.ts
- src/types.ts
A recent PR added `ctx.addIssue` to `transform`: https://github.com/colinhacks/zod/pull/1056
This is fantastic! 
There appears to be a small bug - calling `ctx.addIssue` in `transform` does not work correctly when using `parseAsync`. This results in a confusing behaviour where `parseAsync` and `parse` return different results.
```TypeScript
z
.string()
.transform((val, ctx) => {
const parsed = parseInt(val);
if (isNaN(parsed)) {
ctx.addIssue({
code: z.ZodIssueCode.custom,
message: "Not a number",
});
}
return parsed;
})
.parse("Not a number");
````
__Expected__: Zod error
__Actual__: Success
I've added a test to confirm it is now working correctly. I also took the chance to update the README to reflect this new feature.
> Fix ctx.addIssue in transform to work correctly with parseAsync

- deno/lib/types.ts
- src/__tests__/languageServerFeatures.test.ts
- src/types.ts
Fixes the issue documented here: https://github.com/colinhacks/zod/issues/1121
I'm pretty sure my PR introduced this issue: https://github.com/colinhacks/zod/pull/1117
In almost all cases `z.flatten<{ property: (T | undefined) & T }>` flattens to `{ property: T }`. However, this does not appear to be the case for some very specific types like this one:
```TypeScript
type Opaque<Type, Token = unknown> = Type & { tag: Token };
enum FACE {
QUEEN = "QUEEN",
KING = "KING",
}
enum SUIT {
HEARTS = "HEARTS",
DIAMONDS = "DIAMONDS",
}
type FaceCard<Face extends FACE> = Opaque<`${Face}_${SUIT}`, "FaceCard">;
type Hand = z.objectUtil.flatten<
z.ZodObject<{
card: z.ZodType<FaceCard<FACE.QUEEN>, z.ZodTypeDef, string>;
}>["_output"]
>;
```
In this case `Hand` is flattening to:
```TypeScript
type Hand = …
```
> Restore existing type inference behaviour of z.ZodObject

- deno/lib/ZodError.ts
- deno/lib/__tests__/error.test.ts
- deno/lib/helpers/util.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/error.test.ts
- src/helpers/util.ts
- src/types.ts
Fixes #1042
Small note, I typed the `received` property in `ZodInvalidEnumValueIssue` as `any` since we are returning what was inputed originally, instead of it's `ParsedType`. I think this is right but will wait for confirmation :)
Also added an small util to reduce the code duplication around quoting and joining arrays of strings.
TL;DR;
Given
```ts
enum Fish {
Tuna = "Tuna",
Trout = "Trout"
}
z.nativeEnum(Fish).parse("Salmon");
```
```diff
- "Invalid enum value. Expected 'Tuna' | 'Trout'"
+ "Invalid enum value. Expected 'Tuna' | 'Trout' received 'Salmon'"
```
> Added expected and received properties to enum and native enum

- deno/lib/types.ts
- src/types.ts
Pretty self-explanatory I guess. By using the `@deprecated` tag in JSDoc your IDE will automatically mark the method as deprecated when you use it in your code.
> Improve JSDoc deprecation warning for nonempty

- README.md
I found that the example code for `parseAsync` is wrong.
`.refine` should be passed when the callback returns `true`. Thus, I would like to send a PR 🙇‍♂️
> feat(doc): fix a wrong example at README

- deno/lib/__tests__/recursive.test.ts
- src/__tests__/recursive.test.ts
Recursive implementations frequently utilize union types to represent general and base cases. This PR adds a test case for this, by using a linked list as an illustrative example.
> Add Test for Union Recursive Type

- README.md
This documents the behaviour when passing two arguments to `z.record`.  
I updated the adjacent sections to what I added to make it consistent.
This is open to suggestions.
> Update README for z.record key type schema

- README.md
Link to node points to nothing in readme, changed the link.
Also made the table of content name consistent with the section title and made npm lowercase as it should.
> Fix link to node in readme

- README.md
- To fix the links to individual frameworks in the Table of Contents
> Update README to use headings for validation library names

- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/__tests__/string.test.ts
- src/types.ts
This PR fixes #1246.
`minLength` and `maxLength` are inconsistent in `ZodString`, this PR makes the behaviour more consistent by returning `null` if no max is defined (not changed) and if no min is defined (instead of `-Infinity`).
This PR also improves the syntax by removing the incorrect usage of `Array.map` that had side effects & no return).
A couple tests are also added to make sure it works as intended.
> ZodString.minLength defaults to null to be consistent with maxLength

- README.md
We'd like to add remix-domains in the README (under ecosystem) as our library is only possible due to the existence of Zod <3 and we believe it improves a lot the DX of Remix.
LMK if this PR is welcome or should I make any changes to it.
> Adds remix-domains to the README under Ecosystem

- README.md
- README_ZH.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
This adds a startsWith and endsWith helper on the string like discussed here https://github.com/colinhacks/zod/issues/604
small aside, the playground.ts is missing, which is mentioned in the contrib
> Add string.startsWith and string.endsWith

- README.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/error.test.ts
- deno/lib/__tests__/primitive.test.ts
- deno/lib/helpers/parseUtil.ts
- src/ZodError.ts
- src/__tests__/error.test.ts
- src/__tests__/primitive.test.ts
- src/helpers/parseUtil.ts
This pull request adds support for BigInt literals as discussed here: #1108
> Add BigInt support for literals

- README.md
- README_ZH.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/date.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/date.test.ts
- src/types.ts
This PR fixes #1089.
`ZodDate` now can natively validate for `min` and `max` allowed dates.
> Added native support for min and max date validations

- README.md
- deno/lib/README.md
- deno/lib/__tests__/error.test.ts
- deno/lib/__tests__/recursive.test.ts
- deno/lib/types.ts
- src/__tests__/error.test.ts
- src/__tests__/recursive.test.ts
- src/types.ts
> Don't use invalid_type_error for `undefined` fields.

- README.md
- deno/lib/README.md
Just noticed with ac2fb4a in #1222 `boolean` has been pasted but not replaced with `date` in the docs.
> Replace keyword boolean with date in the docs

- README.md
- deno/lib/README.md
- deno/lib/__tests__/branded.test.ts
- deno/lib/__tests__/firstparty.test.ts
- deno/lib/helpers/util.ts
- deno/lib/types.ts
- src/__tests__/branded.test.ts
- src/__tests__/firstparty.test.ts
- src/helpers/util.ts
- src/types.ts
```ts
const mySchema = z
.object({
name: z.string(),
})
.brand<"mySchema">();
type MySchema = z.infer<typeof mySchema>;
const doStuff = (arg: MySchema) => {}
// works
doStuff(mySchema.parse({ name: "hello there" }));
// fails
doStuff({ name: "hello there!" });
```
> Add branded types

- README.md
Update: Use `.keyof` to create a `ZodEnum` schema from the keys of an object schema.
closes https://github.com/colinhacks/zod/issues/1326
> Update readme keyof typo

- deno/lib/README.md
- deno/lib/types.ts
- src/types.ts
Refs #205
This skips the check for extra keys in the default case of `strip` being the object parsing strategy, because we don't use the extra keys.
This yields a pretty modest performance bump - about 5% in the realworld case in my testing.
> Optimize object strip case

- deno/lib/README.md
- deno/lib/__tests__/refine.test.ts
- deno/lib/types.ts
- src/__tests__/refine.test.ts
- src/types.ts
When using `.refine` with a type guard, the current type definitions are changing the parser's `Input` type. This is inconsistent and causing issues in tRPC where Zod Input types are inferred for client procedure signatures.
This just updates the generic parameter and adds a (previously failing) test for the `Input` type.
> Fix refine with type guard signature

- index.html
Sets docsify [crossOriginLinks](https://docsify.js.org/#/configuration?id=crossoriginlinks) to fix #1468
> [#1468] Fix zod.dev main page cross origin links.

- README.md
- deno/lib/README.md
Since we added the library we have changed it to be framework agnostic, also supporting [Deno](https://deno.land/x/domain_functions@v1.2.0) now. To reflect that shift the library is now called Domain Functions.
> Updates remix-domains library name and description in README

- deno/lib/__tests__/branded.test.ts
- deno/lib/types.ts
- src/__tests__/branded.test.ts
- src/types.ts
A type's brand should only be accessible in its output aka `z.infer` or `z.output` but it's also carried over to its input. This makes it difficult to create a typesafe parse function as the code doesn't compile
For example:
```ts
const Age = z.number().min(18).brand<"Age">()
type AgeInput = z.input<typeof Age>
```
an input for `Age.parse(x)` aka `AgeInput` should just be `number` but it's `number & BRAND<"Age">` which doesn't make sense
[Working typescript playground example](https://www.typescriptlang.org/play?ssl=3&ssc=46&pln=3&pc=1#code/JYWwDg9gTgLgBAbzgLzgXzgMyhEcDkyEAJvgFBkDGEAdgM7wCCA5gKZwC8KAdDQK4gARqygAKAJTcQwGqICMADkmCoAQxrEAPACIWrbQD4JFTHxqUYwWnBx8YI0TLB2AXHH5CR4xGThwwqlB0rI40zjDiZGgmZhZWNP6BwaKqbG7I3E52mjAAnmCsEJhwegbeCFFAA)
> Removed BRAND from ZodBrand Input definition

- ERROR_HANDLING.md
In `ERROR_HANDLING.md`, I changed a code example to use `z.inferFormattedError` from `z.inferFormattedErrors` as the function is implemented as `z.inferFormattedError`
https://github.com/colinhacks/zod/blob/c617ad3edbaf42971485f00042751771c335f9aa/src/ZodError.ts#L167-L170
> Fix typo in ERROR_HANDLING.md

- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/error.test.ts
- src/ZodError.ts
- src/__tests__/error.test.ts
Fixes #1541
It looks like the repo's git hooks added some changes from #1521 that didn't make it into the Deno version. What would you like me to do with these changes? Should they be split into a separate commit, removed, or kept?
> Fix typing bug hiding errors of nullable composite fields

- deno/lib/README.md
- deno/lib/__tests__/partials.test.ts
- deno/lib/types.ts
- src/__tests__/partials.test.ts
- src/types.ts
Hey :wave:
Love zod, we use it in production.. they used to call me the "zod guy" cause I'm the one who introduced it to the codebase. lol.
First time contributing here, sorry If I didn't do things properly.
fixes #1046.
> fix #1046 `.required()` doesn't remove optional flag from the result of `.nullish()`.

- README.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
Adds `.utc()` and `.iso8601()` from https://github.com/colinhacks/zod/issues/126.
Through this PR I learnt that dates can be very inconsistent but still valid 🤯 eg. you can give any number of ms which to me is a little silly. Imagine having `2022-07-08T00:00:00.000Z` alongside `2022-07-08T00:00:00.0000000000000000Z` in your system.
So I've tried to come up with a solution which is flexible but can be customised to be more strict if users wish.
`ms: true` and `ms: false` control whether users want to check for `ms` or not with the default being to accept both formats. I've also added the ability to specify the ms digit precision with `msLength` since technically any number of milliseconds is considered a "valid" timestamp 🙄 .
```ts
// date formats
z.string().utc();
z.string().utc({ ms: …
```
> add `.utc()`/`.iso8601()` string formats

- deno/lib/README.md
- deno/lib/__tests__/discriminatedUnions.test.ts
- deno/lib/types.ts
- src/__tests__/discriminatedUnions.test.ts
- src/types.ts
Fix #1171
Also add support for lazy, refine and superRefine in discriminatedUnions
> #1171 support for refine, superRefine, transform and lazy in discriminatedUnion

- src/types.ts
The `path` parameter is not taken into account when using `.parseAync()` method.
`parseAsync()` calls `safeParseAsync()` with the same params.
However, the line 258 is inconsistent with the similar line 227 of sync method.
```
// in safeParse():
const result = this._parseSync({ data, path: ctx.path, parent: ctx });
// in safeParseAsync()
const maybeAsyncResult = this._parse({ data, path: [], parent: ctx });
```
Therefore, `path` param is ineffective and this PR should fix it.
> Take `path` parameter into account within `.parseAsync()`

- README.md
- deno/lib/README.md
`formik-validator-zod` is a utility library that makes it much easier to use Zod in order to validate Formik form inputs.
It serves a similar purpose to `zod-formik-adapter` but has the added benefit of supporting a greater number of Zod features such as `z.enum`. [Ref](https://github.com/robertLichtnow/zod-formik-adapter/issues/2)
> Add formik-validator-zod to README ecosystem links

- README.md
- deno/lib/README.md
- deno/lib/__tests__/refine.test.ts
- deno/lib/types.ts
- src/__tests__/refine.test.ts
- src/types.ts
Closes #1602.  
Adds TS overloads for `ZodType.superRefine()` such that, if provided with a type predicate function, the signature of the returning `ZodEffects` type will be narrowed. 
Users are still expected to call `ctx.addIssue()` as per the current API. Tests and docs updated.
> feat: #1602 narrow superRefine() type

- deno/lib/ZodError.ts
- deno/lib/__tests__/validations.test.ts
- deno/lib/locales/en.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/validations.test.ts
- src/locales/en.ts
- src/types.ts
closes #1611 
I quickly drafted a working solution so we could iterate and discuss its design.
I also added the same proposed behavior to strings as well, since both strings and arrays share the `.length` function.
Looking further into the codebase, I think it would be ideal to create a new check (something like "exact_legth") and a ZodIssueCode so we can share the same locale behavior between Arrays and Strings.
Whats your take? How should I integrate those changes into Zod's current codebase?
> Fix issue #1611

- README.md
Typos:
1. "to write a functions that accepts a Zod schemas" -> "to write a function that accepts a Zod schema"
2. "for the generate parameter" -> "for the generic parameter"
> docs: fix typo in Writing generic functions

- README.md
_i.e._ means _that is_,
whereas
_e.g._ means _for example_
I'm assuming `.optional()` is just an example here
> docs: likely a minor typo

- README.md
- README_ZH.md
- deno/lib/README.md
I am developing a library to translate zod default error messages into multiple languages. [`zod-i18n-map`](https://github.com/aiji42/zod-i18n)
It is useful and I would like to add it to the ecosystem list.
> docs: add `zod-i18n-map` to README ecosystem links

- deno/lib/__tests__/catch.test.ts
- deno/lib/types.ts
- src/__tests__/catch.test.ts
- src/types.ts
> Only call .catch() method when parsing fails

- README.md
Is it intended to add own projects to the ecosystem area? If no or the linking is not appropriate at this point, I understand if you close the PR.
> Add Modular Forms to form integrations in README

- README.md
> docs: Instruct users to return z.NEVER in .superRefine() when providing a type predicate

- ERROR_HANDLING.md
- deno/lib/README.md
> Fix small typo in ERROR_HANDLING.md

- deno/lib/README.md
- deno/lib/helpers/parseUtil.ts
- src/helpers/parseUtil.ts
This PR updates the `isAsync` type guard to check the `typeof Promise` result against a string literal instead of the `undefined` data type. This change should improve the accuracy and reliability of the function when determining if a value is a Promise.
> Improve accuracy of the `isAsync` type guard

- deno/lib/README.md
- deno/lib/__tests__/catch.test.ts
- deno/lib/types.ts
- src/__tests__/catch.test.ts
- src/types.ts
This PR fixes `ZodCatch`.
It looks like `ZodCatch` was a product of a quick copy-paste from `ZodDefault`, which introduced some bugs to it.
1. The `output` of a `ZodCatch` was previously defined as `util.noUndefined<T["_output"]>` (from `ZodDefault`) when it should actually be `T["_output"] | <<catch value>>`.
2. The `input` of a `ZodCatch` was previously defined as `T["_input"] | undefined` (also from `ZodDefault`) when it should actually be the `T["_input"]` unchanged.
3. Renamed props and methods from `default` to `catch`.
> fix: Fix `ZodCatch`

- README.md
- deno/lib/README.md
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/__tests__/string.test.ts
- src/types.ts
An ISO datetime with an offset without comma should be valid
https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators
> Fix datetime offset without comma

- deno/lib/README.md
- deno/lib/__tests__/number.test.ts
- deno/lib/types.ts
- src/__tests__/number.test.ts
- src/types.ts
Hey 👋 
- Forgot to add `.isFinite` @ #1546.
- A multiple of an integer is an integer, so let's make `.isInt` truthy in that case. This might allow people to ditch `.int()` if all they need is `.multipleOf(int)` but had something that uses `isInt`.
> add `ZodNumber.isFinite`, make `ZodNumber.isInt` true if `.multipleOf(int)`.

- README.md
https://zod.dev/?id=discriminated-unions
``` typescript
…
myUnion.parse({ type: "success", data: "yippie ki yay" });
```
→ :x:
``` json
{
"ZodError": [{
"code": "invalid_union_discriminator",
"options": [
"success",
"failed"
],
"path": [
"status"
],
"message": "Invalid discriminator value. Expected 'success' | 'failed'"
}]
}
```
… because the key we want is `status`, not `type`.
Fix:
``` typescript
myUnion.parse({ status: "success", data: "yippie ki yay" });
```
→ :white_check_mark:
> Discriminated union example fails to parse

- deno/lib/README.md
- deno/lib/__tests__/array.test.ts
- deno/lib/__tests__/tuple.test.ts
- deno/lib/types.ts
- src/__tests__/array.test.ts
- src/__tests__/tuple.test.ts
- src/types.ts
`map()` as referenced in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) is is invoked only for array indexes which have assigned values. It is not invoked for empty slots in sparse arrays. 
In some cases, these slots behave as `undefined` (that would be caught by existing implementation) but in others (e.g. array iteration methods), empty slots are skipped. More info [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#array_methods_and_empty_slots).
Destructing will result in usage of property enumeration instead of iterator which should fix this issue.  
Screenshot for reference.
Fixes both: `ZodTuple` and `ZodArray`. 
Reported in #1693
> fix: [#1693] Tuple with empty items

- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/__tests__/string.test.ts
- src/types.ts
Fixes #1668
I've applied back the changes from #1648, and replaced the nagative lookbehind by a negated set (`[^-]`) and stripped the quantifier from `2` to `1` (`{1,}`) because the negated set is now part of the match.
> fix: #1668 email regex safari compat

- deno/lib/README.md
- deno/lib/types.ts
- src/types.ts
This PR fixes the cascading of the `createParams` to other schemas when using the helper methods provided by `ZodType`.
Previously,
```ts
const MySchema = z
.string({ description: "this is a string schema" })
.optional();
// => No longer has the description associated with it
```
The params would get lost if we called any of the helper methods (`.optional()`, `.nullable()` etc.).
Now:
> fix(#1743): Fix passing params in root class

- deno/lib/__tests__/literal.test.ts
- src/__tests__/literal.test.ts
It is currently throwing due to missing `expect` import.
> fix deno literal test.

- README.md
- deno/lib/README.md
Fixes https://github.com/colinhacks/zod/issues/1443
> Document `.describe()`

- package.json
This PR updates the `homepage` field in the `package.json` file. This way, it will show up on the NPM website. The GH repo link will still be available under "Repository".
> update homepage link in package.json

- README.md
The "Coercion for primitives" section splits up the "String" section and "Datetime validation" subsection. Without this change, "Datetime validation" is a subsection of "Coercion for primitives". This moves the "Coercion for primitives" section right below the "Primitives" section.
---
I am new to zod, so maybe I am missing something, but the readme would make a lot more sense this way.
---
FYI the section was introduced in https://github.com/colinhacks/zod/commit/90bd884bc5c7ebf33437e525cc60f6b7371ff226#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R563 and extended in https://github.com/colinhacks/zod/commit/d7d49e77ccd758ee874f7866862840f88f75cbb6#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R594
> Readme: Move  "Coercion for primitives" section

- README.md
This is based on https://github.com/colinhacks/zod/issues/798#issuecomment-991003983.
I consider it a pretty useful addition which will like save some people some manual research. 
Especially since the solution was not what I was expecting and testing first…
> Readme: Add example for string validation for an optional field to chapter "Unions"

- CHANGELOG.md
The CHANGELOG is significantly out of date, and it seems release notes are now stored in Github Releases only.  This change adds a brief message to redirect users to Github Releases.
> chore(documentation): Update CHANGELOG to redirect to Github Releases

- README.md
- deno/lib/README.md
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/__tests__/string.test.ts
- src/types.ts
It adds support for `[+-]hh` datetime offset, according to https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators.
Example:
```
datetime.parse("2020-10-14T17:42:29+03");
```
> Allow also "[+-]hh" as datetime offset

- README.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
[`cuid`](https://github.com/paralleldrive/cuid) has been deprecated in favour of [`cuid2`](https://github.com/paralleldrive/cuid2). Now it's not yet widely used but I believe it will catch up with `cuid` soon. This PR adds validation for `cuid2`.
It's my first time contributing here so please tell if I did something wrong. I did update the README with the additional method but feel free to revert the change there.
> Add string cuid2() validation

- deno/lib/README.md
- deno/lib/benchmarks/primitives.ts
- src/benchmarks/primitives.ts
This PR will add benchmark tests for date and symbol, currently not covered.
<details>
<summary>yarn benchmark output, only new tests shown</summary>
$ tsx src/benchmarks/index.ts
z.date: valid x 3,007,337 ops/sec ±0.49% (91 runs sampled)
z.date: invalid x 34,043 ops/sec ±3.08% (89 runs sampled)
z.date: valid min and max x 2,141,123 ops/sec ±1.73% (88 runs sampled)
z.date: invalid min x 29,310 ops/sec ±2.43% (87 runs sampled)
z.date: invalid max x 26,036 ops/sec ±3.88% (77 runs sampled)
z.symbol: valid x 5,416,457 ops/sec ±4.04% (79 runs sampled)
z.symbol: invalid x 32,293 ops/sec ±1.95% (78 runs sampled)
</details>
> test: add benchmark tests for date and symbol

- README.md
- deno/lib/README.md
I wrote a form library similar to Formik that uses Zod as its primary field/form validation method called [HouseForm](https://houseform.dev/). I'm using it for production applications today and thought it would be helpful for others to public and document, so we've made it an open-source library that just hit 1.0 today.
> Add React form validation library to ecosystem

- deno/lib/benchmarks/primitives.ts
- src/benchmarks/primitives.ts
Looks like `prettier` wasn't run on some deltas. This should resolve the failing checks [here](https://github.com/colinhacks/zod/actions/runs/4039277062/jobs/6943851558).
> fix: failing prettier checks on merge

- deno/lib/README.md
- deno/lib/__tests__/enum.test.ts
- deno/lib/types.ts
- src/__tests__/enum.test.ts
- src/types.ts
This PR adds two methods to `ZodEnum`:
1. `extract`
2. `exclude`
Both work exactly like the TS utility types of the same name.
You call `.extract()` with values that exist in the enum, and it returns a new one with these values only. The same thing for `.exclude()` but it returns a new enum _without_ the values you passed in.
> feat: Add `extract`/`exclude` methods to `ZodEnum`

- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
For checking that string contains only emojis
> feat: z.string().emoji()

- deno/lib/README.md
- deno/lib/types.ts
- src/types.ts
This PR is an artifact of the discussion.
https://github.com/colinhacks/zod/discussions/2069#discussioncomment-5091931
A `Record` keyed by `string`, `number` or `symbol` is `Non Partial`, but `BRAND` (which should behave similarly) is `Partial`.
This PR ensures that a key with `BRAND` will also be `Non Partial`.
> BRAND Record to Non Partial

- README.md
- deno/lib/README.md
- deno/lib/__tests__/catch.test.ts
- deno/lib/types.ts
- playground.ts
- src/__tests__/catch.test.ts
- src/types.ts
Hey 👋🏻
This PR introduces a way to collect a `ZodError` when using `.catch` method, which can be useful in many case when wanting to collect logs whenever default value is used.
```ts
const numberWithErrorCatch = z.number().catch((e) => {
console.error(e);
return 42;
});
// No error shown in console.
numberWithErrorCatch.parse(5); // => 5
// Default value is returned, an error will be shown in console.
numberWithErrorCatch.parse("tuna"); // => 42
```
> feat: add `.catch` error

- ERROR_HANDLING.md
Makes the example more consistent with the provided explanations above as well as increasing the clarity of the example. Can for example be easy to miss that you need to name the error map variable exactly the same as the property field when passing it this way.
> docs: Update ERROR_HANDLING.md - custom error map example

- deno/lib/ZodError.ts
- src/ZodError.ts
This small refactoring of ZodFormattedError fix several  performance issues in some edge cases.
I did some benchmarks with simple case with typescript compiler option **strict: false**   https://github.com/gydroperit/zod-test-regression
1. Now amount of generated types three times less than before, while  building typescript project, thus almost halves **Check time**
Without fix
```Files:              72
Lines:           30507
Identifiers:     49830
Symbols:         47942
Types:           17794
Instantiations:  29270
Memory used:    77234K
I/O read:        0.00s
I/O write:       0.00s
Parse time:      0.31s
Bind time:       0.13s
Check time:      0.31s
Emit time:       0.01s
Total time:      0.75s
```
with this fix
```
Files:              72
Lines:           30508
Identifiers:     49824 …
```
> Refactoring of ZodFormattedError type to improve tsc check time

- README_ZH.md
docs: improve part of `cn readme` and keep sync with `en readme`
> docs: improve cn readme

- deno/lib/README.md
- deno/lib/types.ts
- playground.ts
- src/types.ts
Hi, thanks for the great library, I adore the API :)
I was looking for ways to make some unintrusive improvements to the performance, and noticed since a ParseInput's path may be evaluated multiple times, caching the evaluation result avoids some extra array allocations.
Around a 10% speedup on 'realworld' on my computer.
Dunno what happened with the rest of the diff, I don't think I touched anything or had "format on save" on...
> Cache the evaluation of ParseInputLazyPath.path() for a moderate perf improvement

- .github/workflows/test.yml
Since TS 5.0 was recently released, I think it's worth it to confirm the general operation of `zod` running this version.
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/
> Testing on Typescript 5.0

- README.md
The old link https://www.typescriptlang.org/docs/handbook/literal-types.html brings us to a deprecated page. This PR update the link to the new page.
> docs: update deprecated link

- README.md
- README_ZH.md
I really like the idea of `zod` so I build my own form integration on it!
Checkout https://mobx-zod-form.pages.dev/ for documentation.
This library takes a different approach to building forms. Zod is where people define everything about their form, as the source of truth, and the form will be built only upon zod.
The library is proved useful in our production and helps us managing huge forms. 
I hope this library will be seen by more people so that other developers and companies could be empowered.
> docs: add mobx-zod-form to form integrations

- README.md
About a week ago I posted on the zod-discord about my project `Zocker`. It was then suggested I make a PR to add it to the added to the Ecosystem section, so here I am. 
Zocker is a mock-data generation library that generates plausible mock-data from zod-schemas, similar to `@anatine/zod-mock`, but supports a wider subset of `zod`. It too uses `faker` under the hood for semantically meaningful data.
A quick overview of what Zocker provides:
- Generation for most zod types (unfortunately not all types are possible to support in a library like this)
- Generation for Regex schemas on strings (thanks to the `randexp` package)
- Cyclic schemas
- Genration for `any` and `unknown` types
- Generation for `map`, `set`, `tuple`, `union` and `record` types
- An API for customising the generation …
> docs: Add `zocker` to Ecosystem section

- package.json
Hey 👋 
This PR re-arranges `package.json`'s `exports` object key order and sets `types` field to first.
This is recommended by TypeScript's official documentation.
> The "types" condition should always come first in "exports".
https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing
> Ensure types condition to be the first. The [TypeScript docs](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing) recommends so, but it's also because the exports field is order-based.
> For example, a scenario where both the types and import condition could be active, types should be first so that it matches and returns a .d.ts file, rather than a .js file from the import condition. …
> chore: move `exports.types` field to first spot @ package.json.

- index.html
This change allows us to test Zod on the documentation site for a simple playground test!
> docs: allow Zod to be used in dev tools at site

- index.html
Added missing deno land link to crossOriginLinks list for docsify.
> Fix not working Deno doc link.

- deno/lib/__tests__/refine.test.ts
- deno/lib/types.ts
- src/__tests__/refine.test.ts
- src/types.ts
Typescript was complaining about the `.superRefine` argument returning a `Promise` when it was expecting a `void` return.
This fixes it so it accepts `Promise<void>` as a valid return value
Attachment of error:
> fix: super refinement function types

- README.md
Zod is brilliant. Thank you for creating and maintaining it.
tRPC is amazing too. It gives you fullstack intellisense without the need for GraphQL (or codegen.) But it still uses GraphQL-like "query" and "mutation" terminology. And [it isn't natively compatible](https://github.com/trpc/trpc/issues/755) with OpenAPI.
Tapiduck is a simpler and RESTful alternative to tRPC. It uses Zod for inferring shape definitions, and for enforcing runtime type validations. It is OpenAPI compatible, built on Express, and should feel familiar to most Node devs.
> docs: add tapiduck to API libraries

- README_ZH.md
- add space between English letters and Chinese characters for readability
- add `as const` example (missing in zh doc) in `zod enums`
> docs: add ts as const example in zod enums

- deno/lib/types.ts
- src/types.ts
This removes a couple of redundant `as any` casts in `createZodEnum`.
> remove "as any" casts in createZodEnum

- README.md
- deno/lib/README.md
This PR adds [koa-zod-router](https://github.com/JakeFenley/koa-zod-router) to the README.
I created this library after using koa-joi-router quite frequently in projects, which works for I/O validation, but lacks type-safety. So I created koa-zod-router to address this and improve upon whats already out there. The library has been used in a few of my own projects in production and is pretty well tested at 99% coverage. For a full list of features please follow the link to the project's repository.
Would just like to say thank you @colinhacks for creating this awesome library, zod has been a fantastic dev experience.
> Add koa-zod-router to README

- README.md
- README_ZH.md
- deno/lib/README.md
This PR corrects the wrong `#partialt` fragment identifier to `#partialtype`.
> docs: fix typo in link fragment

- package.json
Prettier can format code blocks within Markdown the same as the rest of the code. In a recent PR, I noticed that most of my feedback was about code formatting within the README, so I thought this would be helpful.
> Add `*.md` pattern to prettier

- README.md
So update Yup's section of the Zod comparison accordingly.
See: https://github.com/jquense/yup/issues/1906
> docs(comparison-yup): Yup added partial() and deepPartial() in v1

- README.md
- README_ZH.md
- deno/lib/README.md
I started to learn Zod and when I read the documentation, I couldn't understand the example for [Records](https://zod.dev/?id=records), and if it was incomplete. I then tried to find out if I was the only one who didn't understand ;-) I found a discussion here: https://github.com/colinhacks/zod/discussions/1651 
Here's the PR with a more complete example proposed by @JacobWeisenburger
> docs: fix incomplete Records example

- README.md
This adds conform. It didn't look like there was much of an order so I put it at the top since that's where it'd go in alphabetical order anyway 🤷‍♂️
> docs: add conform form integration

- README.md
Adding another plugin I maintain to the list.
For those of you 👀 in this PR:
[fastify-zod-openapi](https://github.com/samchungy/fastify-zod-openapi) adds native Fastify type provider, validator, serializer and @fastify/swagger support for [zod-openapi](https://github.com/samchungy/zod-openapi).
The main difference between this library and `fastify-type-provider-zod` is that it enables support between zod-openapi and Fastify.
> Add `fastify-zod-openapi` to ecosystem

- deno/lib/__tests__/primitive.test.ts
- src/__tests__/primitive.test.ts
While going through the code, I discovered the word "methd", which I believe may be a typographical error for "method". I have proceeded to make the necessary corrections to rectify this typo.
Here's a brief summary of the changes I made:
* All instances of "methd" have been replaced with "method"
> fix typo test name

- .github/workflows/test.yml
- README.md
- deno/lib/README.md
- deno/lib/__tests__/readonly.test.ts
- deno/lib/types.ts
- playground.ts
- src/__tests__/readonly.test.ts
- src/types.ts
- tsconfig.json
A stripped down version of some excellent earlier work by @santosmarco. Marco - at the moment I think it makes sense to always freeze until someone asks to disable it (I don't think they will). I'm also holding off on `.deep()` for the same reason - too much complexity overhead for a feature I'm not sure anyone needs.
cc @tkdodo
> Add ZodReadonly

- deno/lib/__tests__/function.test.ts
- deno/lib/types.ts
- src/__tests__/function.test.ts
- src/types.ts
Uses a non-arrow function to maintain `this`.
Closes #2651
> Initial prototype fix for issue #2651

- README.md
[`typeschema`](https://typeschema.com) offers an universal adapter for `zod` (and any major schema validation lib) that anyone can reuse
> docs: add typeschema to ecosystem

- README.md
Readonly types were introduced in [Zod v3.22.0](https://github.com/colinhacks/zod/releases/tag/v3.22.0).
> docs: remove obsolete text about readonly types

- README.md
Small tweak to clarify docs for `string.datetime()`. current wording is
> "[defaults to UTC validation](https://github.com/colinhacks/zod/blob/1e23990bcdd33d1e81b31e40e77a031fcfd87ce1/README.md?plain=1#L763)"
however, zod actually isn't validating javascript UTC string format (the following will not succeed with `z.string().datetime()`) ❌:
```js
const utcDateTime = new Date().toUTCString(); // Mon, 21 Aug 2023 20:42:52 GMT
```
clarification to show that [it is expecting ISO 8601](https://github.com/colinhacks/zod/blob/1e23990bcdd33d1e81b31e40e77a031fcfd87ce1/deno/lib/types.ts#L581) with no UTC offset. ex ✅:
```js
const isoDateTime = new Date().toISOString(); // 2023-08-21T20:47:22.189Z
```
> clarify datetime format is ISO 8601

- README.md
Hi,
I'm interested in updating the Custom Schemas example in the documentation. The function type takes in an unknown, so the example casts the value to a string in order to operate on it with a RegExp
```typescript
const px = z.custom<`${number}px`>((val) => {
return /^\d+px$/.test(val as string);
});
```
I want to propose using Type Narrowing. It's helped me catch errors from validating a non-expected type, and I believe it would help others as well as a good practice with interacting with the unknown type.
```typescript
const px = z.custom<`${number}px`>((val) => {
return typeof val === "string" ? /^\d+px$/.test(val) : false;
});
```
This is a PR for issue #2718
> #2718 Updated Custom Schemas documentation example to use type narrowing

- ERROR_HANDLING.md
A developer girl should be able to follow the link in the readme to read about discriminated unions and be directed to the new improved documentation.
- Followed original link which informed me of the new documentation. 
- Copy pasted new url
- Opened this here PR
- View old url (https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions) and notice the message.
- Click the link and confirm new url is correct.
> docs: update ref to discriminated-unions

- README.md
- deno/lib/README.md
I am developing a sandbox aplication for testing zod schemas: [`zod-sandbox`](https://zod-sandbox.vercel.app/).
It could be useful and I would like to add it to the ecosystem list.
> docs: add `zod-sandbox` to README ecosystem links

- configs/tsconfig.cjs.json
- deno/lib/README.md
- deno/lib/types.ts
- src/types.ts
I didn't know for a long time that `z.string().nonempty()` was deprecated.
- JSdoc was deleted in `build:cjs`, so prevented it.
- JSdoc was output in the constructor when arrow functions were used in the class, so prevented it.
- Fixed comment not in JSdoc format.
with strike
> Export jsdoc with `@deprecated` when building

- index.html
- yarn.lock
Added the necessary styles to address the issue reported in #2932. Extensive testing has been performed to ensure the changes work seamlessly.
Verified the changes on various devices and screen sizes to confirm responsiveness. Ensured that the styles do not adversely affect other components or layouts.
These changes apply to the entire page body structure. The goal is to enhance the overall user experience and readability, especially on larger screens.
Please review the modifications, and feel free to provide any feedback or suggest further improvements. I'm committed to addressing any concerns promptly.
Closes #2932
> added required styles. 

- README.md
- deno/lib/README.md
> Add documentation to Zod enum exclude/extract functions

- README.md
- deno/lib/README.md
- playground.ts
While the `pipe()` documentation contains a section on how to fix issues with nullish values in `coerce()`. The `coerce()` documentation does not mention that there are issues. This was a pitfall for us. Thus, I'd like to have the nullish value edge cases covered in the `coerce()` section.
Unfortunately, I do not have the language skills to update the Chinese documentation accordingly.
> Add docs for coercing nullish values

- README.md
- deno/lib/README.md
Full disclamer: I'm the maintainer of `zhttp`.
It's a very flexible, typesafe OpenAPI compatible http library. It uses Zod for validation, and for endpoint input and response typing.
> Add zhttp library to docs

- README.md
- ### was reading through docs and saw the typo in this example.
- see the "invalid_type_error" key-value pair below
- changed to :
- ### "isNaN must be 'not a number'"
> fixed Readme typo in NaNs example

- deno/lib/__tests__/error.test.ts
- deno/lib/helpers/parseUtil.ts
- src/__tests__/error.test.ts
- src/helpers/parseUtil.ts
Resolves #3101
Allows setting falsy error messages on validation.
```ts
const schema = z.string().max(1, { message: "" }).parse("aaaa")
// returns error { message: "" }
```
> feature: allow falsy error message

- deno/lib/README.md
- deno/lib/__tests__/enum.test.ts
- deno/lib/types.ts
- src/__tests__/enum.test.ts
- src/types.ts
When calling .extract/exclude we should retain the original RawCreateParams passed to the enum definition. We also allow passing new RawCreateParams if that's necessary. This solves issue #3225.
> Bugfix: Enum.extract/exclude should not remove error mapping

- README.md
- deno/lib/README.md
As I was browsing through the documentation I found that the conform link was out of date (404).
> docs: update link and description of conform integration

- .github/workflows/test.yml
Added Node 20 and TypeScript 5.3
```yaml
matrix:
node: ["18", "20"]
typescript: ["4.5", "4.6", "4.7", "4.8", "4.9", "5.0", "5.3"]
```
Closes #3276 
Closes #3277
> Added latest stable Node and TypeScript versions to test matrix for up-to-date testing.

- src/__tests__/firstpartyschematypes.test.ts
- src/types.ts
Fixes #3246
Some first party schema types were missing from the union. This pull-request adds them, along with a test that tries to keep the union and ambient type declaration in sync.
> Add types to `ZodFirstPartySchemaTypes`

- src/types.ts
More info: https://github.com/trpc/trpc/issues/5538
Unsure if this is a legit fix. I could see this working as designed.
cc @tkdodo @PeterMK85
> fix: make `input` of `.required()` readonly

- README.md
- deno/lib/README.md
- playground.ts
This pull request enhances the documentation for writing generic functions that accept Zod schemas as parameters. The changes address common pitfalls and provide best practices to ensure proper type inference and maintainability.
Key changes:
1. Elaborates the limitations of using `z.ZodType<T>` or `z.ZodSchema<T>` as the type of the input schema.
2. Addresses the issue of parsed data being incorrectly inferred as `any` when using `z.ZodTypeAny`. Provides a solution by leveraging `z.infer<T>` to properly infer the parsed type based on the passed-in schema.
3. Includes code examples to illustrate the limitations of the previous approach and showcases the benefits of using `z.ZodTypeAny`.
Please review the changes and provide any feedback or suggestions for further improvement.
> feat: overhaul generics section of readme to include more details on z.ZodTypeAny usage

- deno/lib/__tests__/safeparse.test.ts
- deno/lib/types.ts
- src/__tests__/safeparse.test.ts
- src/types.ts
Possible improvement to safe parse return types as discussed in #3266.
The `?: never` properties added to the type involve no runtime overhead and support all existing patterns. However, as seen in the tests they avoid casting or intermediate variables when we attempt to access properties on the union `SafeParseReturnType`, since now both branches have the property we attempt to access. When accessing `SafeParseReturnType['data']`, we get `Output | undefined`, which is accurate to the runtime behavior. If we are in a context where we've already checked `success`, we get just `Output` as expected.
> add never props to safe parse return types

- deno/lib/__tests__/discriminated-unions.test.ts
- deno/lib/types.ts
- playground.ts
- src/__tests__/discriminated-unions.test.ts
- src/types.ts
Supports the following as discriminator keys:
- ZodOptional
- ZodNullable
- ZodReadonly
- ZodBranded
- ZodCatch
Also fixes a bug with `z.nativeEnum` as a discriminator key.
> Support more elements in DU

- deno/lib/__tests__/generics.test.ts
- deno/lib/__tests__/object.test.ts
- deno/lib/helpers/util.ts
- playground.ts
- src/__tests__/generics.test.ts
- src/__tests__/object.test.ts
- src/helpers/util.ts
Okay, this is a long time coming. Getting the inferred types to work as expected in generic contexts is quite annoying (see `generics.test.ts` for examples). Some changes I made to that effect seem to interact unhappily with the very specific case described in #2184 - a `ZodObject` schema, with a key corresponding to a union, being cast to `ZodType`.
The change now makes all my tests happy, including assignability in generic contexts and the newly added XOR test.
I'm going to ship this in the next minor since I haven't found a scenario where this breaks or even changes the inferred type signature in non-generic contexts. In generic contexts, it seems to strictly improve assignability characteristics without a big performance hit in the compiler.
cc @chrishoermann
> Improve `addQuestionMarks`, fix #2184

- src/helpers/parseUtil.ts
- src/types.ts
This trivial fix will allow for transpilating to njs.
AFAICS tests pass.
Please consider applying.
> fix for njs

- package.json
Previously, `yarn run test:bun` would fail if we already built for `deno`, since it does not respect the filter in `jest.config.json`, failing with errors like:
```
deno/lib/__tests__/record.test.ts:
error: FileNotFound reading "https://deno.land/x/expect@v0.2.6/mod.ts"
```
> only look in `src` for `bun test`

- deno/lib/helpers/util.ts
- deno/lib/types.ts
- src/helpers/util.ts
- src/types.ts
Both the methods .pick and .omit accept properties that don't exist in the schema.
``` 
const schema = z.object({
existedProperty: z.string(),
});
const pick = schema.pick({
existedProperty: true,
NOT_existed_property: true, // there is no TypeScript error
});
```
Both the methods .pick and .omit now only accept known properties.
``` 
const schema = z.object({
existedProperty: z.string(),
});
const pick = schema.pick({
existedProperty: true,
NOT_existed_property: true, // there is a TypeScript error
});
```
resolves https://github.com/colinhacks/zod/issues/895
> Restrict .pick()/.omit() mask type to only known properties

- README.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/helpers/parseUtil.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
This adds support for [Nano ID](https://www.npmjs.com/package/nanoid), a unique string/id standard. Nano ID is great because it's url friendly, a fixed length, and significantly shorter than UUIDs.
Note: The Nano ID package does allow for a custom character dictionary and id length, however the regex in this PR only matches the default Nano ID specification.
> Adds support for Nano ID

- README.md
- deno/lib/README.md
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- playground.ts
- src/__tests__/string.test.ts
- src/types.ts
See https://en.wikipedia.org/wiki/ISO_8601#Local_time_(unqualified)
Closes #2385
> fix: support local time if no offset

- deno/lib/helpers/parseUtil.ts
- src/helpers/parseUtil.ts
Since `defaultErrorMap` and `getErrorMap()` may return the same one, leads to duplicate in `ZodErrorMap` array. And error mapping can be totally skipped if check message is provided.
https://github.com/colinhacks/zod/blob/master/src/errors.ts#L4-L5
```diff
import defaultErrorMap from "./locales/en";
import type { ZodErrorMap } from "./ZodError";
let overrideErrorMap = defaultErrorMap;
+export { defaultErrorMap };
export function setErrorMap(map: ZodErrorMap) {
overrideErrorMap = map;
}
+export function getErrorMap() {
return overrideErrorMap;
}
```
> perf: avoid unnecessary error maps

- deno/lib/__tests__/enum.test.ts
- deno/lib/__tests__/error.test.ts
- deno/lib/types.ts
- src/__tests__/enum.test.ts
- src/__tests__/error.test.ts
- src/types.ts
Resolves #3146
Make it possible to call enum validation with a custom message using `message` attribute:
```ts
z.enum(['aaa', 'bbb', 'ccc'], { message: 'custom error message' });
```
> feature: add attribute message to enum validatiion

- deno/lib/benchmarks/index.ts
- deno/lib/benchmarks/primitives.ts
- deno/lib/types.ts
- src/benchmarks/index.ts
- src/benchmarks/primitives.ts
- src/types.ts
Improve zod's performance by using `Set.has` instead of `Array.indexOf` when checking for the presence of a value inside `ZodEnum` or `ZodNativeEnum`.
`Array.indexOf` is especially problematic when passing multiple (e.g. 30+) values to an enum. This PR introduces a very simple change that turns an `O(n)` operation to `O(1)`.
- Using `Set.has` we were able to increase the performance of the `parse` method in `ZodEnum` and `ZodNativeEnum` by 20%.
- The more the enum values the greater the benefit by using `Set` instead of `Array`.
> Use Set.has instead of Array.indexOf for enum comparison (perf improvement)

- deno/lib/__tests__/string.test.ts
- src/__tests__/string.test.ts
- src/types.ts
> Fix regex in cuid2 validation to be what cuid2 library expects

- .dependency-cruiser.js
- package.json
Previously the sanity checks in `yarn run depcruise` would fail for two reasons:
1. Benchmark scripts were mistakenly not marked as development-only and were using development dependencies
2. Test code was referencing the `@jest/globals` package, which was an implicit requirement (via `jest`)
Now this script should pass
> Make depcruise pass

- README.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
Hello! This popped up in an [issue over at zod to json schema](https://github.com/StefanTerdell/zod-to-json-schema/issues/95). It feels pretty idiomatic and like something that could have been in Zod since day 1 IMHO, so here we are :)
> Adds base64 string validation

- README.md
First of all, thank you for creating and maintaining the library. I like this.
`Orval` can automatically generate `zod` schema from `OpenAPI`
https://orval.dev/guides/zod
I am currently maintaining this library and would like to recommend it, so I added it to the ecosystem in `README` . If you like this PR, please incorporate it.
> docs: add `orval` to "X to Zod" ecosystems

- .github/pull_request_template.md
- README.md
- deno/lib/README.md
- deno/lib/__tests__/generics.test.ts
- deno/lib/helpers/util.ts
- deno/lib/types.ts
- playground.ts
- src/__tests__/generics.test.ts
- src/helpers/util.ts
- src/types.ts
I'm not sure what the precise reasons for this being faster are, but consistently benchmarking in my project about 50% more type instantiations with the original version vs. the one proposed in this commit; plus the compilation time is 20% longer in the original.
EDIT: check out [this issue comment](https://github.com/microsoft/TypeScript/issues/56017#issuecomment-1755995893) from a `tsc` maintainer
Before:
```
Files:                        1251
Lines of Library:            39145
Lines of Definitions:       126004
Lines of TypeScript:         11878
Lines of JavaScript:             0
Lines of JSON:                   0
Lines of Other:                  0
Identifiers:                183217
Symbols:                    285778
Types:                       99275
Instantiations:            7734511 …
```
> TS compilation perf: faster objectUtil.addQuestionMarks

- README.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
I've added an additional string validator to validate `xid` formatted strings.
Implements the feature requested by #2639 
I've pretty much just done a global search on the codebase for `cuid2`/`ulid`, and added a matching entry for `xid` at each match, making slight changes where necessary.
Let me know if I'm missing anything!
> add xid string validator

- README.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
Add a `.jwt()` validator in string type.
It expects for a string with 3 parts splited by `.` with the first part being a base64 encoded string that represents a objetc wit a property `type` with value `JWT`.
**It validates just format NOT signature.**
Resolves #2946
> Add string jwt

- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
I wanted to use Zod to validate UUIDs, but noticed that the current implementation passes also UUIDs that are actually not valid according to the spec [as defined in RFC4122](https://datatracker.ietf.org/doc/html/rfc4122#section-4).
Namely, the existing regex allows for version and variant values that should not be possible for a UUID.
I created this PR as a proposal in order to have UUID validation follow RFC4122 strictly and add a more generic `guid` string validator that allows for non-conforming UUID-like values (utilising the pre-existing regex making migration as simple as updating `string().uuid`s to `string().guid` where necessary). 
In regards to UUID v6+ I would suggest adding a `uuidv6` (or similar explicitly named) validator until the [RFC …
> Strict RFC4122 UUID validation and separate guid validation

- src/types.ts
Enables creating dynamic schemas from `as const` object definitions:
```typescript
const question = {
questionId: "unit_location",
answers: ["attic", "upstairs", "main_floor", "basement", "garage", "outside", "other"],
} as const;
function questionToZodSchema<
Q extends string,
A extends readonly [string, ...string[]],
>(question: QuestionSpec<Q, A>): z.ZodObject<{ [key in Q]: ZodEnum<A> }> {
return z.object({ [question.questionId]: z.enum(question.answers) }) as any;
}
const schema = leafQuestionToZodSchema(test);
const value = schema.parse({ unit_location: "attic" });
```
Thank you for your contribution to our project! Before submitting your pull request, please ensure the following:
> Made ZodEnum take readonly string array

- README.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/json.test.ts
- deno/lib/types.ts
- playground.ts
- src/ZodError.ts
- src/__tests__/json.test.ts
- src/locales/en.ts
- src/types.ts
Based on https://github.com/colinhacks/zod/issues/3077#issuecomment-1878470503. I started playing around to see how quick it would be to implement, and it ended up being very quick - so opening a PR in hopes the idea is accepted.
Copying from the readme for the `z.string().json(...)` method - the linked issue has more details on the motivation:
The `z.string().json(...)` method parses strings as JSON, then pipes the result to another specified schema.
```ts
const Env = z.object({
API_CONFIG: z.string().json(
z.object({
host: z.string(),
port: z.number().min(1000).max(2000),
})
),
SOME_OTHER_VALUE: z.string(),
});
const env = Env.parse({
API_CONFIG: '{ "host": "example.com", "port": 1234 }',
SOME_OTHER_VALUE: "abc123",
});
env.API_CONFIG.host; // returns parsed value
```
If invalid JSON is …
> Add z.string().json(...) helper

- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/record.test.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/helpers/parseUtil.ts
- deno/lib/types.ts
- src/__tests__/record.test.ts
- src/helpers/parseUtil.ts
- src/types.ts
`ZodRecord` and `ZodObject` `_parse` methods are dealing differently with undefined values which seems inconsistent.
Problem described further in this issue: #2762 .
I added the same logic to the `_parse` method in `ZodRecord` as implemented  in `ZodObject`.
closes #2762
> Allow undefined values in record, similar to object.

- README.md
Happy to share the link to Zod Playground: [Zod Playground](https://zod-playground.vercel.app/). It's a tool designed for instant testing of Zod schemas. 
I hope you find it useful! Any feedback you have to improve it further would be greatly appreciated.
> Add Zod playground link

- README.md
- src/__tests__/readonly.test.ts
- src/types.ts
Hello!
I noticed that the parsed results of `readonly()` schemas are not really readonly after `parseAsync()`
I added tests, then a fix. (and corrected a minor typo in the related docs)
> Fixed freezing async ZodReadonly results

- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/error.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/error.test.ts
- yarn.lock
This PR is to resolve issue #2183, which is to make inferFlattenedErrors be of type input, even for schemas with transforms defined.
I'm new to writing PRs, so I wasn't sure of the etiquette, and I'm not sure of the differences in the README, so I'd be glad to hear your comments.
> Fix[#2183] inferFlattenedErrors should be a type about input type

- deno/lib/helpers/util.ts
- src/helpers/util.ts
Fixes the issue described [here](https://github.com/colinhacks/zod/issues/3437), at least the minimal repro example provided.
Benchmarking the change using [zod-ts-perftest](https://github.com/jussisaurio/zod-ts-perftest) it increases the number of type instantiations by 8.5%, which may be an acceptable compromise, but ofc not ideal
[More discussion here](https://github.com/colinhacks/zod/pull/2845#issuecomment-2093772277)
> Fix #3437: extendShape erases JSDoc property documentation

- ERROR_HANDLING.md
- README.md
- deno/lib/README.md
- deno/lib/locales/fa.ts
- package.json
- src/locales/fa.ts
- add zod/locales/fa.js
- change ERROR_HANDLING.md
linked issue: https://github.com/colinhacks/zod/issues/2855#issue-1936617590
> Add Persian(Farsi) language errorMap

- README.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
Hello, following the previous [discussion](https://github.com/colinhacks/zod/issues/3378), I added validation for the E.164 format on strings using a modified regex from this [article](https://blog.stevenlevithan.com/archives/validate-phone-number#r4-3).  I removed support for spaces as those don't seem to be [permitted](https://gotrunk.com/blog/the-e-164-format-what-is-it-and-how-to-use-it-correctly/#:~:text=How%20to%20dial%20an%20E.164%20phone%20number%20correctly). The validation could be further enhanced by prohibiting `0` as the first value since country codes start with `1`.
There is an alternative regular expression from the [Twilio docs](https://www.twilio.com/docs/glossary/what-e164#regex-matching-for-e164) for E.164 numbers. This regular expression permits very short E.164 …
> Add E.164 format validation for strings

- .configs/tsconfig.types.json
- benchmarks/benchUtil.ts
- benchmarks/package.json
- package.json
- packages/effect-plugin/package.json
- packages/zod/package.json
- pnpm-lock.yaml
Switch from `ts-node` to `tsx` — [docs](https://tsx.is/)
Built-in watch mode so we can drop `nodemon` too 💯
> Switch to tsx

- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/__tests__/string.test.ts
- src/types.ts
- Modification of the regex validating ULIDs to make it case insensitive
- Adding a unit test to validate this
> Fix issue #3582 : ULID should be case insensitive

- README.md
[zod-schema-faker](https://github.com/soc221b/zod-schema-faker)  is a feature-complete tool designed to seamlessly integrate with Zod, enabling developers to generate realistic mock data based on Zod schemas.
> docs: add zod-schema-faker to ecosystem

- packages/zod/src/locales/de.ts
- packages/zod/src/locales/es.ts
- packages/zod/src/locales/fr.ts
- packages/zod/src/locales/pt-br.ts
- packages/zod/src/locales/pt-pt.ts
- packages/zod/src/locales/de.ts
- packages/zod/src/locales/es.ts
- packages/zod/src/locales/fr.ts
- packages/zod/src/locales/pt-br.ts
- packages/zod/src/locales/pt-pt.ts
> Add de, es, fr, pt-br, pt-pt locales

- README.md
Add [drizzle-zod](https://orm.drizzle.team/docs/zod) library to README.md section for generating Zod definitions from Drizzle ORM definitions, placed below the Prisma entry under the X to Zod section.
> Add drizzle-zod library to X to Zod README.md section

- .configs/tsconfig.base.json
- biome.jsonc
- package.json
- packages/effect-plugin/package.json
- packages/zod/package.json
- pnpm-lock.yaml
- vitest.root.mts
These changes make it possible to do regular development on Zod without doing any local builds. All tests run against source files, and inter-package imports just work.
- Add `@zod/source` to point to TypeScript source using tshy's `sourceDialects`
- Use `customConditions` in tsconfig.json to tell TypeScript to incorporate `@zod/source` condition into module resolution
- Update `resolve.conditions` in Vitest root config so imports to workspace packages reference source code
> Implement live types

- README.md
Hello there,
thank you for this awesome library!
We've built a form renderer utility which generates react-hook-form fields from a zod schema by using type mapping.
It is available as [open source](https://github.com/thepeaklab/zod-form-renderer) and it would be awesome if we could use your "Form integrations" section to promote it.
Thanks and best regards!
> docs: add zod-form-renderer to form integration docs

- README.md
I make a plugin for loading and parse environment variable into virtual modules and provided type definition and 80% using power of `Zod`. This plugin support with rollup, rolldown, esbuild, webpack, nextjs, vite, astro, and more (based on unjs/unplugin).
Thanks for @colinhacks for make this (`zod`) over-power library.
> docs: add unplugin-environment in powered by zod

- deno/lib/README.md
- deno/lib/types.ts
- src/types.ts
In this PR, I only renamed the type to IpVersion to improve consistency.
> refactor: Rename IP version types

- ERROR_HANDLING.md
Fixes invalid syntax that prevents code example from being copy-pasted.
> docs: Remove invalid semicolon in ERROR_HANDLING.md

- README.md
- README_ZH.md
Since Deno now supports installing directly from npm, no differentiation is required between npm/bun and deno. We can streamline the install guide.
This PR updates the readme to:
- remove the dedicated section on importing from deno.land as this is no longer required (in English and Simplified Chinese files)
- add `deno add` example (in English and Simplified Chinese files)
- add `deno add` example for canary
This update has been tested against the provided basic usage examples to validate that it works as expected.
> Simplifying installation guide now that Deno supports installing from npm

- README.md
- deno/lib/README.md
This feature was added in [version 3.23.0](https://github.com/colinhacks/zod/releases/tag/v3.23.0).
> docs: add info on unqualified local datetime strings

- ERROR_HANDLING.md
- README.md
- README_ZH.md
- deno/lib/README.md
- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
> Add support for `base64url` strings

- deno/lib/__tests__/discriminated-unions.test.ts
- deno/lib/types.ts
- src/__tests__/discriminated-unions.test.ts
- src/types.ts
If I extract the array of options out of the `z.discriminatedUnion` call, type-checking fails because an array is not assignable to a non-empty tuple:
```ts
const options = [
z.object({ type: z.literal("x"), val: z.literal(1) }),
z.object({ type: z.literal("y"), val: z.literal(2) }),
];
const schema = z.discriminatedUnion("type", options);
```
```
TS2345: Argument of type '(ZodObject<{ type: ZodLiteral<"x">; val: ZodLiteral<1>; }, "strip", ZodTypeAny, { type: "x"; val: 1; }, { type: "x"; val: 1; }> | ZodObject<{ type: ZodLiteral<...>; val: ZodLiteral<...>; }, "strip", ZodTypeAny, { ...; }, { ...; }>)[]' is not assignable to parameter of type '[ZodDiscriminatedUnionOption<"type">, ...ZodDiscriminatedUnionOption<"type">[]]'.
Source provides no match for required element at position 0 in …
```
> Allow creation of discriminated unions with a readonly array of options

- deno/lib/__tests__/description.test.ts
- deno/lib/types.ts
- src/__tests__/description.test.ts
- src/types.ts
See [this issue](https://github.com/colinhacks/zod/issues/3529) for more context.
Basically, the description for a type was getting unexpectedly duplicated when using `.array()`. For example:
```typescript
z.string().describe("a description").array()
// ^ was functionally the same as v
z.array(
z.string().describe("a description")
).describe("a description")
```
The issue was not present for `z.array()`
```typescript
z.array(z.string().describe("a description")) // works as expected
```
This unexpected behavior was introduced in a fix trying to ensure that something like `z.string().describe("a description").optional()` persisted the description after being wrapped by `ZodOptional`.
While this behavior makes sense for types like `ZodOptional` or `ZodNullable`, `ZodArray` is a completely …
> Remove createParams cascade from .array()

- deno/lib/__tests__/standard-schema.test.ts
- deno/lib/standard-schema.ts
- deno/lib/types.ts
- package.json
- playground.ts
- src/__tests__/standard-schema.test.ts
- src/standard-schema.ts
- src/types.ts
- yarn.lock
Implement the [Standard Schema](https://github.com/standard-schema/standard-schema) specification.
> Implement Standard Schema spec

- deno/lib/ZodError.ts
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/ZodError.ts
- src/__tests__/string.test.ts
- src/types.ts
This PR retroactively implements the jwt string format in Zod v3. Resolves #2946 
Supports the following API:
```ts
z.string().jwt() // checks for jwt format
z.string().jwt({ alg?: string }) // with optional algorithm
```
Implements:
- A three-part JWT structure (header.payload.signature), with base64 encoding of all parts and header containing required 'typ' and 'alg' fields.
- Optional algorithm validation when specified
- Implement in both main and Deno versions
- Add comprehensive test coverage
Link to Devin run: https://preview.devin.ai/sessions/51826709fcd3457abc4be25e587c790c
> feat: Add JWT string validator

- README.md
- deno/lib/README.md
Thank you Courier!
https://github.com/user-attachments/assets/6b09506a-78de-47e8-a8c1-792efe31910a
> Add Courier to README

- README.md
The url for runtyping was incorrect.  The correct url to the github page should be [https://github.com/johngeorgewright/runtyping](https://github.com/johngeorgewright/runtyping)
> docs(X to Zod): Update url for runtyping

- packages/docs/app/(doc)/[[...slug]]/page.tsx
- packages/docs/components/accordion.tsx
- packages/docs/components/tabs.tsx
This PR replaces Fumadocs Tabs with tabs that never unmount, so tab content can be easily ingested
> Keep tabs unmounted

- packages/docs/content/v4/changelog.mdx
I noticed a function definition improperly using `const` in place of `function` when working through the migration guide.
> Fix improper function definition in migration guide

- packages/docs/content/v4/index.mdx
Added `git switch v4` to the benchmark instructions, as the `bench` command doesn’t work unless you're on the `v4` branch.
> Update benchmark instructions to include switching to the v4 branch

- packages/core/src/to-json-schema.ts
- packages/zod/tests/json-schema.test.ts
https://json-schema.org/understanding-json-schema/reference/const
> `.toJSONSchema()`: Prefer `const` over `enum` for single literal

- packages/core/src/to-json-schema.ts
- packages/zod/tests/json-schema.test.ts
Addresses https://github.com/colinhacks/zod/issues/4120 by implementing approach 2: adding both `format` and `pattern` regardless of `format`, supposedly [the best practice](https://www.learnjsonschema.com/2020-12/format-annotation/format/). This does increase the schema payload size, which should be largely irrelevant for most purposes of json schema.
> Add pattern to json schema if present

- packages/zod/src/schemas.ts
- packages/zod/tests/string.test.ts
While checking the operation of v4, I noticed that the second argument option of the regex method does not work.
> Fix params option to work with regex method

- packages/core/src/schemas.ts
- packages/zod/tests/async-parsing.test.ts
Fixed a bug where asynchronous check logic did not work properly
I discovered that while asynchronous processes that are executed immediately, such as `Promise.resolve`, work properly in `refine` and `check`, if an asynchronous process that takes time to process is passed, all asynchronous processes are not executed.
The cause seems to be that the `check` process chains asynchronous processes, but the chained processes cannot be defined.
> Fix does not work async check logic

- packages/core/src/locales/en.ts
- packages/core/tests/locales/en.test.ts
- packages/mini/tests/object.test.ts
- packages/zod/tests/object.test.ts
When passing a Object.create(null) object (a " null -prototype object") the parseType function errors because it cannot read the name from the constructor.
Fastify test suite uses these null prototype objects for some reason.
> fix (v4): check for null prototype in parsedType function

- packages/core/src/to-json-schema.ts
- packages/zod/tests/json-schema.test.ts
https://github.com/colinhacks/zod/issues/4089
`.optional()` and `.nonoptional()` shouldn't actually change our type as optionality and nullability are different things.
I've changed it to just pipe through our inner type.
> `.toJSONSchema()` Fix optional behaviour

- packages/docs/content/packages/core.mdx
> fix(docs): Typo in word from

- packages/docs/content/api.mdx
It looks like the comments were interchanged. To my understanding, obj: A will pass because the property in the interface A is optional, whereas obj: B will fail because it is not optional.
> fix(docs): wrong comment for object document

- biome.jsonc
- packages/core/src/util.ts
- packages/mini/src/schemas.ts
- packages/tsc/bench/lots-of-objects.ts
- packages/tsc/bench/object-with-extend.ts
- packages/tsc/bench/omit-extend.ts
- packages/tsc/bench/string.ts
- packages/tsc/bench/strongly-connected.ts
- packages/tsc/bisect.ts
- packages/tsc/extend.ts
- packages/tsc/generate.ts
- packages/tsc/package.json
- packages/zod/src/schemas.ts
- play.ts
- pnpm-lock.yaml
This targets v4 and it's basically the same change as in https://github.com/colinhacks/zod/pull/4150 (but that targets v3).
The proposed version is better because it preserves declaration links and that helps in-IDE navigation. To get proper declaration links you need to iterate over a single "modifier object" and `[P in keyof T | keyof U]` breaks that (it sources keys from 2 objects, so the compiler can't decide from which one the declaration, and modifiers, should be picked from). See this [TS playground](https://www.typescriptlang.org/play/?ssl=3&ssc=23&pln=3&pc=47#code/C4TwDgpgBAthBOBzCBGAPAFQDRQKoD4oBeKAeRgEthMcBrCEAewDMoMoAyKep1gzvAG4AUKEiwEyAEw08hEjxZsBivlAgAPYBAB2AEwDOUHRABuCKAH5lXXFABcZStWzcGS9l1VyBuEWOg4JAgAZll+EgBvKABtAAUoCh03XmUAHxSlXABdRwTNbX0jbztrXHjshzZ4lXdWDEqAXxFRcGgAMUZGY …
> Refactor `Extend` to preserve declaration links

- packages/docs/content/basics.mdx
- Removed redundant whitespaces before `string()` method
- Fixed typo in the note to `.parse()` method
Resolves Issue: `v4: docs typo in the note to .parse() method` [#4146](https://github.com/colinhacks/zod/issues/4146)
> v4: fix typos in basics guide

- packages/docs/content/api.mdx
fixed a typo for the constant`colors`
> v4: fix typo in defining schemas section

- packages/docs/content/v4/changelog.mdx
Just read through the migration guide docs and noticed a few typos so here's a quick PR.
> v4: fix migration guide typos

- packages/docs/content/api.mdx
> fix(docs): Correct "with with" typo.

- packages/docs/content/api.mdx
Correct typo in Records "that as" instead of "that is".
> fix(docs): Correct typo in Records

- packages/docs/content/api.mdx
Update documentation to clarify that optional properties in `z.interface()` are defined with a `?` suffix, not a prefix.
> fix(docs): Typo in `z.object()` vs `z.interface()`

- packages/docs/components/ecosystem.tsx
Thank you for your excellent work on Zod v4!
[GQLoom](https://github.com/modevol-com/gqloom) now fully supports Zod v4 and has been released in the [next version](https://github.com/modevol-com/gqloom/pull/41).
Install using the `next` tag:
```bash
npm install zod@next @gqloom/zod@next
yarn add zod@next @gqloom/zod@next
pnpm add zod@next @gqloom/zod@next
```
I really love Zod v4, especially the `register` feature, which enables GQLoom to define GraphQL-specific metadata directly on Zod:
```ts
const Orange = z
.object({
name: z.string(),
color: z.string(),
prize: z.number(),
})
.register(asObjectType, { name: "Orange", interfaces: [Fruit] })
```
> v4: add GQLoom to ecosystem

- packages/docs/content/api.mdx
The code samples in `.exclude()` belong to `.extract()` and vice versa.
> fix(docs): Swap Enum `.exclude() / .extract()` code samples.

- packages/core/src/json-schema.ts
- packages/core/src/registries.ts
- packages/core/src/schemas.ts
- packages/core/src/to-json-schema.ts
- packages/core/src/util.ts
- packages/docs/content/error-customization.mdx
- packages/mini/src/schemas.ts
- packages/zod/src/schemas.ts
- packages/zod/tests/json-schema.test.ts
- play.ts
- vitest.root.mts
> Improve handling of `.meta()`/`.describe()` in JSON Schema converter

- packages/docs/content/v4/changelog.mdx
I found a missing comment in the migration guide and fixed it.
> docs: fixed missing comment in migration guide

- packages/docs/content/v4/changelog.mdx
Just a small typo I noticed while reading through the (excellent!) migration guide
> fix migration guide typo

- packages/docs/components/ecosystem.tsx
Thanks for Zod 4!
Adding zod-config back to the v4 ecosystem.
[Zod Config](https://github.com/alexmarqs/zod-config) is supporting Zod 4 via [Pre-Release / Release Candidate](https://github.com/alexmarqs/zod-config/releases/tag/v1.0.0-rc.0) (until Zod 4 it's stable).
Install using the rc tag:
```
npm install zod-config@rc
yarn add zod-config@rc
pnpm add zod-config@rc
```
> Add "zod-config" to ecosystem.tsx (v4 support via pre-release)

- packages/docs/components/ecosystem.tsx
Hey everyone!
Thanks for opening an issue the other day. I also got a heads-up from @colinhacks about upgrading to Zod v4 over here:
https://github.com/kubb-labs/kubb/issues/1663
Good news—we’ve confirmed that Zod v4 works smoothly with Kubb, everything’s looking good on our end. We’ll keep working on supporting the latest features in Zod v4. This already lets us drop some of our custom TypeScript helpers, thanks to the new `z.interface` 🙌.
Thanks
> Add support for `kubb` as part of the v4 upgrade

- packages/docs/content/error-formatting.mdx
- Make schema a strict object
- Add extra key to induce error described later
____
Quoting https://github.com/colinhacks/zod/issues/4213#issuecomment-2841705047 directly:
I've noticed something about the `treeifyError()` function in v4 related to the documentation:
In the documentation example, the errors array contains values:
```json5
{
errors: [ 'Unrecognized key: "extraKey"' ],
// ...
}
```
However, in the original issue's example code, the errors arrays are empty, and I've observed the same behavior in my own testing:
```json5
{
"errors": [],
"properties": {
"coworkers": {
"errors": [],
// ...
}
}
}
```
This inconsistency between documentation and actual behavior makes it harder to understand how to properly use and interpret the results of `treeifyError()`. Could we get …
> Correct conditions for error in docs

- packages/docs/content/packages/mini.mdx
A zod code sample is importing from @zod/mini, this change only updates the import line to match the library it should be coming from.
> correction in documentation

- packages/docs/content/v4/changelog.mdx
The following commit removed the deprecated mark from strict():
https://github.com/colinhacks/zod/commit/4d269a2f379914ab5b8be7f7a33e959cf2e2d53d
And this was an omission from the guide, so I fixed it.
https://github.com/colinhacks/zod/pull/4289#issuecomment-2842957366
> docs: in v4, `strict()` is not deprecated

- packages/docs/components/ecosystem.tsx
HI everyone, Thank you for creating an issue the other day.
I received an issue from @colinhacks  here with information about upgrading to v4:
https://github.com/orval-labs/orval/issues/2042
I have confirmed that v4 is compatible with orval, so I will continue to set up links as part of the ecosystem after v4 👍
> chore: add `orval` to XtoZod ecosystems in v4

- packages/docs/components/ecosystem.tsx
- packages/docs/content/v4/changelog.mdx
Hey folks! Thank you for opening the issue seasonedcc/composable-functions#174 the other day!
And congrats for all the work-zod@4 and zod/min have been a pleasure to work with!
As our library supports @standard-schema I already imagined it would work with zod@4 without any changes and I was right:
seasonedcc/composable-functions#176
I hope we get added to the v4 as zod has been a crucial part of the development of Composable Functions.
Cheers and LMK if I should change anything
> Add composable-functions as a library powered by Zod supporting v4

- biome.jsonc
- packages/core/src/api.ts
- packages/core/src/schemas.ts
- packages/core/src/util.ts
- packages/core/src/versions.ts
- packages/docs/content/api.mdx
- packages/docs/content/basics.mdx
- packages/docs/content/index.mdx
- packages/docs/content/json-schema.mdx
- packages/docs/content/packages/core.mdx
- packages/docs/content/packages/zod.mdx
- packages/docs/content/v4/changelog.mdx
- packages/docs/content/v4/index.mdx
- packages/mini/src/schemas.ts
- packages/tsc/bench/strongly-connected.ts
- packages/tsc/bisect.ts
- packages/tsc/generate.ts
- packages/zod/src/schemas.ts
- play.ts
- v4.md
Drop `z.interface()` from docs
> Drop `z.interface()` from docs

- README.md
- deno/lib/README.md
- deno/lib/__tests__/string.test.ts
- deno/lib/types.ts
- src/__tests__/string.test.ts
- src/types.ts
Addresses #3636 
This updates the time regex to be in line with the ISO8601 spec that allows seconds to be omitted.
These strings are also `Date`-compatible: 
```javascript
> new Date('2024-01-01T00:00Z')
2024-01-01T00:00:00.000Z
> new Date('2024-01-01T00:00+0500')
2023-12-31T19:00:00.000Z
> new Date('2024-01-01T00:00')
2024-01-01T08:00:00.000Z
```
> Allow HH:MM format in `z.string().datetime()` and `z.string().time()`

- packages/core/src/to-json-schema.ts
This pull request solves the problem of generating a json schema when the minimum/maximum is zero and does not fall into the schema.
```ts
import { z } from 'zod';
const User = z.strictObject({
gt: z.number().gt(0),
gte: z.number().gte(0),
lt: z.number().lt(0),
lte: z.number().lte(0),
positive: z.number().positive(),
negative: z.number().negative(),
str: z.string().min(0),
arr: z.array(z.number()).min(0),
});
console.dir(z.toJSONSchema(User), {depth: null});
```
> V4(fix): generate json-schema with min/max(0)

- packages/core/src/schemas.ts
fixes https://github.com/colinhacks/zod/issues/4329
tested with a local patched version so far.
feel free to reject this and fix it a different way, or if I am not following the pr process correctly for zod.
> fix(v4): use input, not output, for input of `$ZodUnionInternals`

- packages/docs/content/api.mdx
- packages/zod/src/v4/classic/schemas.ts
- packages/zod/src/v4/classic/tests/string.test.ts
- packages/zod/src/v4/core/regexes.ts
- packages/zod/src/v4/core/schemas.ts
- packages/zod/src/v4/mini/tests/string.test.ts
- play.ts
This drops the more restrictive hostname check that existed in earlier versions of Zod 4. Instead, this adds support for optional `protocol` and `hostname` regexes. 
By default Zod still validates the `hostname` against this much more forgiving regex:
```ts
export const hostname: RegExp = /^([a-zA-Z0-9-]+\.)*[a-zA-Z0-9-]+$/;
```
---
To validate any WHATWG-compatible URL.
```ts
const schema = z.url();
schema.parse("https://example.com"); // ✅
schema.parse("http://localhost"); // ✅
schema.parse("mailto:noreply@zod.dev"); // ❌
schema.parse("sup"); // ❌
```
To validate the hostname against a specific regex:
```ts
const schema = z.url({ hostname: /^example.com$/ });
schema.parse("https://example.com"); // ✅
schema.parse("https://zombo.com"); // ❌
```
To validate the protocol against a specific …
> Improve `z.url()`: support `hostname` and `protocol` regexes

- packages/zod/src/v4/core/core.ts
- packages/zod/src/v4/core/schemas.ts
- play.ts
Run this before any Zod code:
```ts
import { z } from "zod/v4"
z.config({ jitless: true })
```
This short-circuits all code paths that would call `eval`/`new Function`. 
Some runtimes (Next middleware) seem to detect usage of these APIs during build-time. Fixing that will require something more involved.
> Add `jitless` flag to avoid `eval`/`new Function`

- packages/zod/src/v4/classic/tests/json-schema.test.ts
- packages/zod/src/v4/core/to-json-schema.ts
> v4: set `additionalProperties` to `false` when catchall is never

- packages/docs/content/api.mdx
The Documentation for V4 has an example for using `z.url` with the `hostname` option. It looks like this:
```ts
const schema = z.url({ hostname: /^example.com$/ });
```
This allows `example.com`, but it also allows hostnames like `exampleacom`, which is not intended. Probably not an Issue here, but it might make it possible to sneak in unintended Hostnames on certain URLs if devs aren't careful. 
This PR explicitly escapes the `.` in the example to reduce mistakes. 
```ts
const schema = z.url({ hostname: /^example\.com$/ });
```
> v4 docs: Escape `.` in example Regex for `z.url` with `hostname`

- packages/zod/src/v4/classic/coerce.ts
- packages/zod/src/v4/classic/tests/coerce.test.ts
- packages/zod/src/v4/core/schemas.ts
- packages/zod/src/v4/mini/coerce.ts
- play.ts
Support an optional generic parameter on `z.coerce.string()`, etc.
```ts
const a = z.coerce.string<any>();
type Ain = z.input<typeof a>; // any
const b = z.coerce.string();
type Bin = z.input<typeof a>; // unknown
```
This also lets TypeScript set the input type appropriately in inference-constrained environments.
```
import { z } from "zod/v4";
z.pipe(z.string(), z.coerce.number());
```
> Allow generic on coerce functions

- packages/zod/src/v4/classic/tests/pipe.test.ts
- packages/zod/src/v4/core/schemas.ts
Fixed a bug in handling the error value of `catchValue` in the pipe schema.
The value defined in catch is not set in the following schema.
```ts
const stringWithDefault = z
.pipe(
z.transform((v) => (v === "none" ? undefined : v)),
z.string()
)
.catch("default");
expect(stringWithDefault.parse(undefined)).toBe("default"); // <-- The value is set to `undefined`.
```
> Fix: $ZodCatch schema catchValue handling on validation error

- packages/zod/src/v4/classic/tests/error-utils.test.ts
- packages/zod/src/v4/core/errors.ts
This should also correctly handle even weirder stuff like newlines in proeprty keys. JSON.stringify should do all the right escaping - if it's a valid JSON string, it's a valid key.
Note: one existing test was updated:
```ts
expect(z.core.toDotPath(["data[0]", "value"])).toMatchInlineSnapshot(`"data[0].value"`); // <- before
expect(z.core.toDotPath(["data[0]", "value"])).toMatchInlineSnapshot(`"["data[0]"].value"`); // <- after
```
This looks correct to me: Previously it was implying a shape of
`{data: [{value: '...'}]}` when actually it should be a shape of
`{'data[0]': {value: '...'}}`
> fix: use JSON.stringify to escape toDotPath keys w/ quotes

- packages/bench/object-moltar.ts
- packages/zod/src/v4/classic/tests/object.test.ts
- packages/zod/src/v4/core/doc.ts
- packages/zod/src/v4/core/schemas.ts
- play.ts
Modified the JIT pass for object parsing to preserve the shape key order in the result objects. Slight perf hit (~5%). I assumed it would be far more dramatic. I think it's worthwhile to preserve Zod 3 behavior.
> Preserve shape key ordering in result

- packages/bench/discriminated-union.ts
- packages/bench/jit-union.ts
- packages/bench/package.json
- packages/docs/content/api.mdx
- packages/zod/src/v4/classic/schemas.ts
- packages/zod/src/v4/classic/tests/discriminated-unions.test.ts
- packages/zod/src/v4/classic/tests/index.test.ts
- packages/zod/src/v4/core/api.ts
- packages/zod/src/v4/core/doc.ts
- packages/zod/src/v4/core/schemas.ts
- packages/zod/src/v4/mini/schemas.ts
- packages/zod/src/v4/mini/tests/index.test.ts
- play.ts
- pnpm-lock.yaml
Unfortunately a last-minute breaking change (sort of) here. TLDR: You need to continue specifying the discriminator key:
```ts
// ✅
z.discriminatedUnion("type", [
z.object({ type: z.literal("a"), a: z.string() }),
z.object({ type: z.literal("b"), b: z.string() }),
]);
// ❌
z.discriminatedUnion([
z.object({ type: z.literal("a"), a: z.string() }),
z.object({ type: z.literal("b"), b: z.string() }),
]);
```
In earlier betas there was no need to specify the discriminator key. But I'm adding it back now for a couple reasons:
1. The old implementation was getting unnecessarily hairy. There were edge cases I didn't anticipate: https://github.com/colinhacks/zod/issues/4399
2. From an API design perspective, specifying a discriminator is not difficult, and in fact kind of nice. 
3. Bundle size: An …
> Add back discriminator to `z.discriminatedUnion()` API

- packages/docs/components/ecosystem.tsx
- packages/zod/src/v3/helpers/partialUtil.ts
- packages/zod/src/v4/classic/tests/lazy.test.ts
- packages/zod/src/v4/classic/tests/optional.test.ts
- packages/zod/src/v4/classic/tests/pickomit.test.ts
- packages/zod/src/v4/core/schemas.ts
- packages/zod/src/v4/core/to-json-schema.ts
- packages/zod/src/v4/core/util.ts
- packages/zod/src/v4/mini/tests/object.test.ts
- play.ts
Closes https://github.com/colinhacks/zod/issues/4322
> Implement pipe optionality. Drop `._zod.optionality` in favor of `._zod.optin` and `._zod.optout`.

- packages/docs/content/basics.mdx
`if` clause was using `error` naming, but binding was called `err`. Renamed to `error` to follow more of Zod error naming
> fix: basics.mdx error typo

- packages/zod/src/v4/core/registries.ts
- Loosen type of `examples` to `unknown[]` (from `$output[]`)
- Adds `example` 
- Adds `deprecated`
Why loosen the type?
- Everything is simpler if Zod dumbly patches all metadata to the generated JSON Schema. Getting too clever just makes things surprising and is bad DX. 
- Sidesteps concerns about whether `examples` should accept input or output types https://github.com/colinhacks/zod/issues/4516
- Allows for OpenAPI's record-style `examples` field: https://swagger.io/docs/specification/v3_0/adding-examples/
- Avoids materializing the inferred types, which prevents circularity errors when using `.meta()` on recursive schemas https://github.com/colinhacks/zod/issues/4570
- Users who want to do typechecking on their examples can opt-in with `satisfies z.output<typeof MySchema>`
Closes …
> Loosen and expand metadata typing

- packages/docs/content/api.mdx
Noticed a tiny typo. 
Changed 
> If you only care about validating inputs, _omit the `output` field is optional._
to
> If you only care about validating inputs, _**you can** omit the `output` field **as it** is optional._
Tried to keep your prose style intact.
> minor grammar typo fix

- packages/zod/src/v4/core/schemas.ts
I'd suggest to configure ESLint/Biome to prevent this
> Removing `console.dir` from `$ZodDiscriminatedUnion`

- packages/docs/content/api.mdx
- packages/docs/content/v4/index.mdx
This seems like some little mistakes in the docs :)
> docs: fix some typos on the "Defining schemas" page

- packages/docs/content/api.mdx
Zod 4 (colinhacks#4074)
- Remove `z.literal(Symbol("terrific"));` from docs in api.mdx
> fix(docs): remove z.literal(Symbol)

- packages/zod/src/v4/classic/tests/to-json-schema.test.ts
followup of: #4577
fixes: #4249
probably also fixes: https://github.com/vercel/ai/pull/6421#issuecomment-2925378022
Since google and other packages like swagger expects a `type` in it so adding support for it will be better I think
> fix: add type to literal enum

- packages/zod/README.md
The instance of error being used doesn't exist within the context of the example.
> Replace non existing error instance.

- packages/docs/content/error-customization.mdx
- packages/zod/src/v4/locales/index.ts
- packages/zod/src/v4/locales/ps.ts
This PR adds Pashto (ps) locale support to Zod, enabling validation error messages.
> feat(locale): Add Pashto (ps) locale support

- packages/docs/content/api.mdx
> fix #4700: Use array as argument of templateLiteral

- packages/zod/src/v4/core/api.ts
**Description:**  
This PR corrects a minor typo in a comment within `api.ts`, ensuring consistency and clarity in documentation.
> Fix typo in comment: "defaults" instead of "defaults"

- packages/docs/components/ecosystem.tsx
**Summary:**
This PR adds [zod-validation-error](https://github.com/causaly/zod-validation-error) to the [Ecosystem](https://zod.dev/ecosystem?id=form-integrations) page to highlight it as a useful utility for formatting and handling Zod validation errors in a developer-friendly way.
**Why:**
To improve discoverability of helpful tooling.
> chore(docs): include zod-validation-error lib to Ecosystem page

- .vscode/settings.json
- packages/zod/src/v4/classic/schemas.ts
- packages/zod/src/v4/classic/tests/string-formats.test.ts
- packages/zod/src/v4/core/api.ts
- packages/zod/src/v4/core/checks.ts
- packages/zod/src/v4/core/schemas.ts
- packages/zod/src/v4/mini/schemas.ts
- play.ts
Implement `z.stringFormat()` to enable custom string format schemas. 
```ts
// function form
const a = z.stringFormat("creditCard", (val) => /\d{16}/.test(val))
// regex form
const b = z.stringFormat("creditCard",  /\d{16}/)
```
These schemas produce proper `invalid_format` issues, unlike a naive approach with `z.custom()` or `.refine()`:
```ts
const b = z.stringFormat("creditCard", /\d{16}/);
b.parse("asdf");
// ZodError: [
//   {
//     code: "invalid_format",
//     format: "creditCard",
//     path: [],
//     message: "Invalid creditCard",
//   },
// ];
```
> Add `z.stringFormat()`

- packages/docs/content/metadata.mdx
I was surprised to encounter uniqueness checks on the `id` property of metadata for my custom registry.  Based on #4145, this feature is intentional.  So, I figured I would update the docs!
That said, I do wonder if the uniqueness check should be reserved for the global registry.  My custom registry has nothing to do with JSON Schema generation.  My `id` property was meant to be a `boolean`, which controls something about a custom Zod-Mongoose integration I'm working on.
Anyway, thanks for the truly outstanding library.
> Docs: Warn about `id` uniqueness check on Metadata page

- packages/zod/src/v4/classic/tests/object.test.ts
- packages/zod/src/v4/classic/tests/optional.test.ts
- packages/zod/src/v4/classic/tests/to-json-schema.test.ts
- packages/zod/src/v4/core/schemas.ts
- packages/zod/src/v4/core/to-json-schema.ts
- play.ts
Resolves https://github.com/colinhacks/zod/issues/4768
Changes:
- Marks `.catch()` schemas as input optional.
- Marks `.never()` schemas as input and output optional.
- Marks `.undefined()` schemas as input and output optional.
- Changes `.undefined()` output to align with `.never()`. At the moment it outputs `null` which isn't strictly correct. The Zod Schema would never be able to accept `null`. We essentially want them to send us nothing right? As `undefined` doesn't exist we can treat it the same as `.never()`
- Marks `z.union()` schemas with optional members as `input` and `output` optional.
> Fix optionality of schemas

- packages/docs/content/error-formatting.mdx
📝 Pull Request Description
Purpose
This PR updates the documentation for z.flattenError() in ERROR_HANDLING.md to correct the output example. It ensures the example accurately matches the actual return structure of the function.
Changes Made
Replaced incorrect properties:
flattened.fieldErrors.string → flattened.properties.username
flattened.fieldErrors.numbers → flattened.properties.favoriteNumbers
Removed outdated reference to formErrors and replaced it with errors
Context & Justification
The current documentation example displays outdated key names that differ from the actual API behavior. This discrepancy could cause confusion for users relying on these docs. This update aligns examples with real behavior, improving clarity and accuracy.
Related Issue
Closes #4819
> docs: fix typo in flattenError example on error-formatting page (#4819)

- packages/docs/components/ecosystem-v3.tsx
- packages/docs/components/ecosystem.tsx
Adds my [zod2md](https://github.com/matejchalk/zod2md) library to _Zod to X_ section of _Ecosystem_ docs page. Both Zod v4 and Zod v3 are supported by this library. (The migration approach described in #4371 helped a lot, BTW.)
> docs: add zod2md to zodToXConverters

- packages/docs/content/api.mdx
Fix refine() when() example copy-pasted comment.
> docs: fix refine() when() example copy-pasted comment

- packages/zod/src/v4/classic/tests/file.test.ts
- packages/zod/src/v4/core/schemas.ts
> fixes `z.core.File` type incompatibility with `globalThis.File`

- packages/docs/content/api.mdx
From the tests, it looks like `z.enum` supports object literal comprehension out-of-the-box:
https://github.com/colinhacks/zod/blob/3048d14bc7b803507302b8ee3cd1eeeffbd27396/packages/zod/src/v4/classic/tests/enum.test.ts#L12-L24
But it doesn't look like the rest of the world realizes it. Googling for "zod z.enum object literal" leads me to stackoverflow discussions ([1](https://stackoverflow.com/questions/73825273/creating-a-zod-enum-from-an-object), [2](https://stackoverflow.com/questions/75217817/zod-enum-and-object-as-const)) that keep trying to use `Object.values` or other stuff to get this working. I don't really understand. Cursor is yelling at me for no good reason:
Updates the documentation with an object literal example, in the hopes that this knowledge propagates and people stop …
> Update docs z.enum with object literal example

- packages/docs/content/error-formatting.mdx
Doc says "two issues" but the example shows three
> Fix number of errors in doc

- packages/bench/index.ts
- packages/bench/object-moltar.ts
- packages/treeshake/package.json
- packages/treeshake/rollup.config.js
- packages/zod/src/v4/classic/schemas.ts
- packages/zod/src/v4/core/schemas.ts
Before:
```
$ pnpm bundle zod-mini-object.ts
> @zod/treeshaking@ bundle /Users/colinmcd94/Documents/projects/zod/packages/treeshake
> rollup -c rollup.config.js --input zod-mini-object.ts
zod-mini-object.ts → ./out.js...
┌──────────────────────────────┐
│                              │
│   Destination: ./out.js      │
│   Bundle Size:  24.49 KB     │
│   Minified Size:  11.73 KB   │
│   Gzipped Size:  3.91 KB     │
│                              │
└──────────────────────────────┘
created ./out.js in 968ms
```
After: 
```
$ pnpm bundle zod-mini-object.ts
> @zod/treeshaking@ bundle /Users/colinmcd94/Documents/projects/zod/packages/treeshake
> rollup -c rollup.config.js --input zod-mini-object.ts
zod-mini-object.ts → ./out.js...
┌────────────────────────────┐
│                            │
│ …
```
> Drop JIT in Zod Mini `z.object()` (reduces bundle size by 20%)

- packages/docs/app/(doc)/[[...slug]]/page.tsx
While checking the [migration guide](https://zod.dev/v4/changelog) from z3 to z4 I saw that the `edit this page` button was redirecting to incorrect path,
Redirecting page on the official site:
The correct path:
> fix: `edit this page` button, now redirects to correct url using the new path

- packages/docs/components/ecosystem-v3.tsx
This should make Hey API more relevant when people search for things like "openapi zod 3"
> Update Hey API link to Zod v3 plugin

- packages/docs/components/ecosystem.tsx
This should make Hey API more relevant when people search for things like "openapi zod"
> Update Hey API link to Zod plugin

- packages/docs/components/ecosystem.tsx
Adds `nestjs-zod` to ecosystem.  It supports zod v4, has 100k downloads per week, and 784 stars
> Add `nestjs-zod` to ecosystem

- packages/zod/src/v4/classic/tests/to-json-schema.test.ts
- packages/zod/src/v4/core/to-json-schema.ts
- really closes #5143
- fixes oversight of #5145
---
In #5145 I forgot that `items` shouldn't be an array...
but an object with a `oneOf` property which is the array containing the items:
Sorry about the fuss 😅
> fix(v4): toJSONSchema - add missing oneOf inside items in tuple conversion

- packages/zod/src/v4/classic/tests/to-json-schema.test.ts
- packages/zod/src/v4/core/to-json-schema.ts
Fixes #5151
Resolves issue where tuple schemas with rest elements and metadata IDs generated incorrect internal paths when targeting draft-7, causing improper schema extraction and reference generation.
- Fixed hardcoded path names in tuple processing to be target-aware
- Added regression test
> fix(v4): toJSONSchema tuple path handling for draft-7 with metadata IDs

- packages/zod/src/v4/classic/tests/to-json-schema.test.ts
- packages/zod/src/v4/core/to-json-schema.ts
- closes #5140
---
Previously, the code applied to all drafts except `"draft-4"`.
Since `openapi-3.0` doesn’t require `propertyNames`, 
I inverted the condition to explicitly state when it should be included, rather than relying on exclusion.
> fix(v4): toJSONSchema - wrong record output when targeting `openapi-3.0`

- packages/zod/src/v4/classic/tests/to-json-schema.test.ts
- packages/zod/src/v4/core/to-json-schema.ts
> fix(v4): toJSONSchema - output numbers with exclusive range correctly when targeting `openapi-3.0`

- packages/docs/content/codecs.mdx
Just a small docs change, currently the first `encode` marked as passes also fails due to > 2000 check
> docs: fix refine fn to encode works properly

- packages/docs/content/api.mdx
This PR corrects the example of `z.looseObject` API to use `LooseDog` schema instead of `Dog`, which should address confusion and improve clarity.
> fix(docs): correct example to use `LooseDog` instead of `Dog`

- packages/docs/content/api.mdx
This PR addresses issue #5180 by fixing a variable naming inconsistency in the documentation for Zod's coercion feature. The code example in the "Customizing the input type" section had a mismatch between the variable declaration and its usage in type definitions.
In the documentation at https://zod.dev/api?id=coercion, under the "Customizing the input type" accordion section, there was a code snippet demonstrating how to work with coercion schemas:
```typescript
// Before (incorrect):
const regular = z.coerce.string();
type RegularInput = z.input<typeof regularCoerce>; // => unknown
type RegularOutput = z.output<typeof regularCoerce>; // => string
```
The variable was declared as `regular` but referenced as `regularCoerce` in the subsequent type definitions, which would cause a …
> Fix variable name inconsistency in coercion documentation code example

- packages/zod/src/v4/classic/schemas.ts
- packages/zod/src/v4/classic/tests/recursive-types.test.ts
- packages/zod/src/v4/core/schemas.ts
- packages/zod/src/v4/mini/schemas.ts
- play.ts
> Fix shape caching

- packages/zod/src/v3/ZodError.ts
Uses Object.create(null) to create a prototype-less error object, avoiding collisions with built-in Object properties.Issue #5265
> fix(ZodError): prevent flatten() from crashing on 'toString' key
