colinhacks/zod

README.md

Love this project, thank you! The table of contents had a broken link.

Fixed a readme link

---

src/types/string.ts

Switched from regex to URL constructor when validating URLs

---

README.md
src/ZodError.ts
src/__tests__/map.tests.ts
src/codegen.ts
src/index.ts
src/isScalar.ts
src/parser.ts
src/types/base.ts
src/types/map.ts
tsconfig.json

Add z.map() to support Map objects

---

package.json

Removes empty `dependencies` key & adds `funding` link.
Relates to #225.

Add `package.json` enhancements

---

README.md

Adds the most important takeaways from #238 to the README.

V2 document transformers and refinements

---

package.json

- #225
Based on the documentation [described here](https://github.com/nodejs/package-maintenance/blob/main/docs/PACKAGE-SUPPORT.md#support-backing)
Please be informed there are a lot of different options, so it might be worth checking the document yourself @colinhacks as I might have missed something valuable.
P.S. we haven't fully resolved the issue with formatting yet, as you can see I added a new line in the `package.json` changes.
I was thinking about fixing it, but decided to keep it so it's clearer why I create a new PR on the remaining aspects of formatting

Added support backing information

---

INTEGRATIONS.MD

Following the discussion on #86.
Created an INTEGRATIONS.md file, and added docs on integrating Zod with Mongoose in it.
I haven't got to integrate Zod with other relevant libraries (yet), so I couldn't add guides for other libraries.

create INTEGRATIONS.md & add mongoose docs

---

ERROR_HANDLING.md

Fixes a broken link to the default error map

Fix URL to default error map

---

README.md

- also removed yarn instructions. Having both are confusing for those new to node ecosystem. Yarn users will know what to do.

docs: corrected install instructions in readme for v3

---

src/__tests__/keyof.test.ts
src/index.ts
src/parser.ts
src/types/base.ts
src/types/keyof.ts
src/types/nativeEnum.ts

https://github.com/colinhacks/zod/issues/286

Add .keyof

---

README.md

- Missing lazy/recursive types
https://github.com/gcanti/io-ts/blob/master/Decoder.md#the-lazy-combinator
- Missing union & intersection schemas
https://github.com/gcanti/io-ts/blob/master/Decoder.md#the-union-combinator
https://github.com/gcanti/io-ts/blob/master/Decoder.md#the-intersect-combinator
- Missing support for parsing cyclical data (maybe)
https://github.com/gcanti/io-ts/blob/master/Decoder.md#the-lazy-combinator
- Missing error customization 
it has built in error reporter, tho as error is just a data structure you can implement your own error reporter
https://github.com/gcanti/io-ts/blob/master/Decoder.md#built-in-error-reporter

update io-ts comparison

---

deno/lib/ZodError.ts
src/ZodError.ts

Hi @colinhacks!
Please, review this PR - I've applied fix from https://github.com/colinhacks/zod/commit/7142f7d33a5071a589df798461f3e11b6311fd16

fix setPrototypeOf in v3

---

deno/lib/types.ts
src/types.ts

Note: Unsure of the handling around ZodNonEmptyArray.

Add type discriminator to zod type

---

README.md
deno/lib/types.ts
src/types.ts

Add promise() to ZodType

---

README.md

Also added a link to the live page for the converter

Add json to zod in ecosystem

---

README.md

Hey,
I accidentaly another converter; this time from Json schemas to Zod. It's still early but it works well enough for my use cases so I thought I'd add it to the list. ✌️

Added json-schema-to-zod to ecosystem

---

README.md

chore: add soly package to ecosystem

---

README.md

https://github.com/sachinraja/zod-to-ts

add zod-to-ts to ecosystem

---

README_ZH.md

In this pull request, I have translated multiple headers and contents that have not been translated fully into Chinese.

Further translate untranslated English parts

---

README_ZH.md

The same as https://github.com/colinhacks/zod/pull/835 but I'm too lazy to join them.

Fix mistake in example (README_ZH.md)

---

README.md

Fix mistake in example (README.md)

---

deno/lib/types.ts
src/types.ts

fix: Add `description` to `ProcessedCreateParams`

---

README.md

Encourage users to use Zod, by asking them to Join the Discord server, Explore the Docs, and to Install Zod.

Add badges and call to action to README

---

package.json

Add `types` field to `exports` in `package.json`

---

README.md

It would be really cool have this mentioned here 🙏

Add react-zorm to "Form integrations" section

---

README.md

Also added a filter for the master branch, so only relevant tests are shown

fix(readme): Use Correct Test Link

---

README.md

While reading the docs I noticed a small typo. 
Micro pull request to correct! 👍

Small typo in readme (contraining => constraining)

---

README.md

Added `nestjs-graphql-zod` library to the Ecosystem.

Add `nestjs-graphql-zod` to ecosystem links

---

deno/lib/__tests__/default.test.ts
deno/lib/declarations.d.ts
src/__tests__/default.test.ts

I wasn't sure about how defaults worked with enums so I played around a bit. I thought they may be worth adding to the test suite :)

Added test for enums with defaults

---

README.md

Convert "an nullable" to "a nullable"

---

README.md

Super quick fix for example on README.

Fix: transform example on README

---

README.md
deno/lib/README.md

This adds zodios to zod ecosystem

docs: add zodios to zod ecosystem

---

README.md
README_ZH.md
deno/lib/README.md

Hi - we recently became a sponsor - thanks for making zod possible

Added Avana Wallet as sponsor

---

README.md

Many thanks for the awesome project. I added `zod` to `@runtyping`, which converts static types & JSON schema to `zod`.
Here's a link if you'd like to add it to your "ecosystem" list.

Add @runtyping/zod to ecosystem list

---

README.md

Previous links were leading to 404

docs: fix links to anatine plugins in README

---

deno/lib/README.md
deno/lib/ZodError.ts
deno/lib/__tests__/error.test.ts
src/ZodError.ts
src/__tests__/error.test.ts

add `fatal` to `ZodIssue`.

---

README.md
deno/lib/README.md
deno/lib/ZodError.ts
deno/lib/__tests__/number.test.ts
deno/lib/locales/en.ts
deno/lib/types.ts
src/ZodError.ts
src/__tests__/number.test.ts
src/locales/en.ts
src/types.ts

add `.finite()` @ `ZodNumber`.

---

README.md

[znv](https://github.com/lostfictions/znv) is a library for parsing environment variables with zod.

Add znv to the Ecosystem

---

deno/lib/README.md
deno/lib/__tests__/string.test.ts
deno/lib/types.ts
src/__tests__/string.test.ts
src/types.ts

[hyphen `-`, provided that it is not the first or last character.](https://en.wikipedia.org/wiki/Email_address#Domain)

fix: #1638 and Redundant character escape '\' in RegExp

---

CONTRIBUTING.md

docs: update CONTRIBUTING.md links

---

src/types.ts

Solves https://github.com/colinhacks/zod/discussions/1565

change the chaining order of nullish method

---

deno/lib/ZodError.ts
src/ZodError.ts

Propagate custom error type to ZodFormattedError subfields

---

ERROR_HANDLING.md

- null check missing `props` prefix and optional check
- ya i copy pasted it so what

fix: compile error in sample code

---

README.md

To make the docs easier to navigate.

Readme: Add internal links "or" <-> "union"

---

README.md

I was trying to understand what zod literals are. The docs could benefit from an intro sentence. This is a suggestion for such an intro. However, this can probably be more specific. For example, which differences are there to TS literal types? Eg. with Symbol and BigInt (which I both know nothing about…).

Readme: Add intro to chapter Literals

---

deno/lib/README.md
deno/lib/__tests__/catch.test.ts
deno/lib/types.ts
playground.ts
src/__tests__/catch.test.ts
src/types.ts

fix: [#1839] remove caught errors from issues

---

deno/lib/README.md
index.html
static/moon.svg
static/sun.svg

fix: [#1784] dark mode in the documentation

---

src/types.ts

Issue: https://github.com/colinhacks/zod/issues/2003

export the email regex

---

README.md
deno/lib/README.md

Hopefully an easy PR to merge.

docs: punctuation

---

README.md

Thanks for Zod, great library!
Quick PR to improve the clarity of the variable name `data`

Improve variable name clarity

---

README_ZH.md

readme-zh: add missing `)`

---

.github/workflows/release-canary.yml

I _think_ this is what we need?

Fix npm canary action paths pattern

---

README.md

Heya just a PR to add my library to the list 😄
https://github.com/samchungy/zod-openapi
For those of you looking here, the main differences between this one and other ones is a much simpler API to create and register components.

Add `zod-openapi` to ecosystem

---

README.md

👋 Hi, I like this library so I created the zod-fixture library based on Auto Fixure (from the .NET world).
It helps us with the generation of test data.
GitHub link: https://github.com/timdeschryver/zod-fixture
NPM link: https://www.npmjs.com/package/zod-fixture
An Example:
```ts
import { z } from 'zod';
import { createFixture } from 'zod-fixture';
const PersonSchema = z.object({
name: z.string(),
birthday: z.date(),
address: z.object({
street: z.string(),
city: z.string(),
state: z.string(),
}),
pets: z.array(z.object({ name: z.string(), breed: z.string() })),
totalVisits: z.number(),
});
const person = createFixture(PersonSchema);
```
Gives you the following value for person:
```json
{
"name": "name-b1d5c46c-ec89-4fd5-abdf-b263ae808b84",
"birthday": "2021-01-11T23:58:00.091Z", …
```

docs: add zod-fixture to mocking ecosystem

---

deno/lib/README.md
deno/lib/__tests__/record.test.ts
deno/lib/helpers/parseUtil.ts
src/__tests__/record.test.ts
src/helpers/parseUtil.ts

Fixes the minor vulnerability described [here](https://github.com/colinhacks/zod/issues/2227)

Fix proto pollution vulnerability

---

README.md

I add [VeeValidate](https://vee-validate.logaretm.com/v4/integrations/zod-schema-validation/) Zod Schema Validation to the list.

docs: add VeeValidate form library for Vue.js

---

README.md
README_ZH.md
deno/lib/README.md

This follows on from https://github.com/colinhacks/zod/pull/1702, to keep the docs in sync.

Update `nullish()` documentation to correct chaining order

---

README.md

Closes https://github.com/colinhacks/zod/issues/2948

chore: add pastel package to ecosystem

---

README.md
deno/lib/README.md

Adds `zod-dev` utility to eco-system section

---

README.md

Introducing `zod-config`: load configuration variables from multiple sources with flexible adapters, ensuring type safety with Zod.
Links:
- https://github.com/alexmarqs/zod-config 
- https://www.npmjs.com/package/zod-config
Main features:
- Tiny. Zod Config is a tiny library with no dependencies, tree-shaking friendly;
- Flexible. Combine multiple adapters to load the configuration from different sources. We deeply merge the configuration from different sources, following the order of the adapters provided; Create your own adapters easily; Use the callback functions to handle errors and success due to the async nature of the adapters;
- Easy to use. Zod Config is designed to be easy to use, with a simple API;
cc @colinhacks 🙏 🚀

adds zod-config library to the ecosystem

---

README.md

We love Zod!
It powers the ability to define any schema and then visually edit the props in our sidebar ([example](https://watercolor-map.vercel.app)).
We barely have any other dependencies, but Zod is just perfect and think is gonna be useful forever, no matter how many hypecycles we go through. Thanks for making this!
If you don't mind, we'll add ourselves to the list of sponsors, been one since April.

Add Remotion as Bronze sponsor

---

README.md

https://github.com/duplojs/duplojs-zod-accelerator

Add zod-accelerator to ecosystem utilities

---

README.md

New Maven plugin I have released

Add java-to-zod in X to Zod section

---

README.md
deno/lib/README.md

**IMPORTANT:** Development of the next major version of Zod (`v4`) is currently ongoing. If your PR implements new functionality, it should target the `v4` branch, NOT the `master` branch. (If it's a bugfix, the `master` branch is fine.)
Thank you for your contribution to our project! Before submitting your pull request, please ensure the following:

docs: correct typo

---

.github/workflows/release-canary.yml
.github/workflows/release.yml

**IMPORTANT:** Development of the next major version of Zod (`v4`) is currently ongoing. If your PR implements new functionality, it should target the `v4` branch, NOT the `master` branch. (If it's a bugfix, the `master` branch is fine.)
https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow
https://github.com/marketplace/actions/npm-publish#github-action
Gotta get you the ✅ on npm
Not sure if contents needs to be write but I see in the CI that your pipeline pushes up to GitHub. Pull request read is for your change log step which appears to read pull requests.

Publish with Provenance

---

README.md
deno/lib/README.md
deno/lib/ZodError.ts
deno/lib/__tests__/file.test.ts
deno/lib/__tests__/firstparty.test.ts
deno/lib/helpers/util.ts
deno/lib/locales/en.ts
deno/lib/types.ts
package.json
src/ZodError.ts
src/__tests__/file.test.ts
src/__tests__/firstparty.test.ts
src/helpers/util.ts
src/locales/en.ts
src/types.ts
yarn.lock

https://github.com/colinhacks/zod/issues/2846
Keen on the feedback. Cheers.

Add support for `file` validation

---

README.md
deno/lib/README.md
deno/lib/ZodError.ts
deno/lib/__tests__/string.test.ts
deno/lib/types.ts
src/ZodError.ts
src/__tests__/string.test.ts
src/helpers/parseUtil.ts
src/types.ts
yarn.lock

feat: add support for KSUIDs

---

.github/pull_request_template.md
README.md
deno/lib/README.md

Update sponsor tiers

---

deno/lib/__tests__/string.test.ts
deno/lib/types.ts
src/__tests__/string.test.ts
src/types.ts

- allow only URLs with valid hostname and forbid TLD without subdomains
Fixes https://github.com/colinhacks/zod/issues/2236

fix: make URL validation more strict

---

README.md
deno/lib/README.md

Thank you for your contribution to our project! Before submitting your pull request, please ensure the following:

Add Bronze logos

---

README_ZH.md

The content of Discriminated unions does not appear in the Chinese README, here is the complementary

Update README_ZH.md about Discriminated unions

---

.gitignore
.vscode/launch.json
.vscode/settings.json
README.md
deno/lib/README.md

Add Encore.dev to sponsors

---

README.md
deno/lib/README.md

[Speakeasy](https://www.speakeasyapi.dev/) is Zod's first platinum sponsor 🕺

Add Speakeasy under new Platinum tier

---

README.md
deno/lib/README.md

Add [Stainless](https://stainlessapi.com) as a Platinum sponsor

Add Stainless to sponsors

---

README.md
blog/index.html
deno/lib/README.md
index.html

Update Clerk artwork

---

README.md
deno/lib/README.md

Socket.IO solution with I/O validation and the ability to generate AsyncAPI specification and a contract for consumers

Add `zod-sockets`

---

README.md
deno/lib/README.md

Thanks Retool!
<picture height="100px">
<source media="(prefers-color-scheme: dark)" srcset="https://github.com/colinhacks/zod/assets/3084745/ac65013f-aeb4-48dd-a2ee-41040b69cbe6">
</picture>

Add Retool as Platinum sponsor

---

README.md
deno/lib/README.md

Adding [Neon](https://neon.tech) to Platinum sponsors

Add Neon to sponsors

---

README.md

Add light theme version of the Neon logo

Update Neon logo

---

README.md
deno/lib/README.md

Add Val Town as sponsor

---

README.md

https://github.com/commonbaseapp/zodex

Add zodex to README

---

README.md
deno/lib/README.md

Add LibLab as Platinum sponsor

---

README.md

I've created a small adapter package that should simplify Zod integration with Antd forms.
Any feedback is welcome.

Add antd-zod form integration

---

README.md

Add oas-tszod-gen to API libraries section.

Add API library

---

README.md

`zod-struct` is a utility to create simple structs using Zod schemas.

Add `zod-struct` to utilities for Zod

---

README.md

Recently I've [released Runtypes 7](https://github.com/runtypes/runtypes/releases/tag/v7.0.0) and things changed a bit.

Update comparison with Runtypes in `README.md`

---

README.md

the path of [zod-dto](https://github.com/kbkk/abitia/tree/main/packages/zod-dto) is incorrect.

fix: redirect url to correct url

---

README.md
deno/lib/README.md

Feature Mintlify

---

README.md
deno/lib/README.md

Update mintlify feature

---

README.md
deno/lib/README.md

Add Chromatic as feature sponsor

---

README.md
deno/lib/README.md

While many libraries exist, I prefer Zod for its clean API. Thanks for creating this lib.

docs: add oRPC to Ecosystem

---

packages/docs/app/layout.config.tsx
packages/docs/content/basics.mdx
packages/docs/content/index.mdx

Related to #4100 
Hi all, this PR fixes these small issues raised on [https://github.com/colinhacks/zod/issues/4100](url)

fixes typos + logo margin issue

---

packages/core/src/locales.ts
packages/core/src/locales/az.ts
packages/docs/content/error-customization.mdx

Added initial Azerbaijani locale.

feat(lang): Added initial Azerbaijani locale

---

packages/docs/content/api.mdx

Correct grammatical error in Refinements

fix(docs): Grammatical error in Refinements

---

packages/docs/components/ecosystem-v3.tsx
packages/docs/components/ecosystem.tsx

In my previous MR you said to edit `components/ecosystem.mdx` but couldn't find it, if it was a typo i guessed it was this file! 👍

docs: added @regle/schemas to form ecosystem

---

packages/zod/src/v4/classic/tests/json-schema.test.ts
packages/zod/src/v4/core/core.ts
packages/zod/src/v4/core/json-schema.ts
packages/zod/src/v4/core/to-json-schema.ts
play.ts

`z.toJSONSchema`: Defer execution of `override`, improve ref handling

---

packages/docs/content/v4/changelog.mdx
packages/zod/src/v4/classic/tests/json-schema.test.ts
packages/zod/src/v4/classic/tests/string.test.ts
packages/zod/src/v4/core/regexes.ts
packages/zod/src/v4/core/schemas.ts
play.ts

Improve base64 perf. Disallow padding in base64url.

---

packages/zod/src/v4/classic/tests/json-schema.test.ts
packages/zod/src/v4/core/to-json-schema.ts
play.ts

Closes https://github.com/colinhacks/zod/issues/4299

Add `$schema` in `z.toJSONSchema`

---

packages/docs/content/basics.mdx

Change to safeParse

---

packages/docs/content/error-customization.mdx

Hello!
I fixed a small mistake in the docs.

Fix documentation in v4

---

packages/zod/src/v3/tests/refine.test.ts
packages/zod/src/v3/types.ts
packages/zod/src/v4/classic/tests/to-json-schema.test.ts
packages/zod/src/v4/core/to-json-schema.ts
play.ts

Closes https://github.com/colinhacks/zod/issues/4548

Use output type for preprocess

---

packages/zod/src/v3/tests/refine.test.ts
packages/zod/src/v3/types.ts
play.ts

Port of #4266 to the v4 codebase
Closes https://github.com/colinhacks/zod/issues/2243
Closes https://github.com/colinhacks/zod/issues/2192
Closes https://github.com/colinhacks/zod/issues/2113

Abort further processing when transform is skipped

---

packages/docs/content/api.mdx
packages/docs/content/json-schema.mdx
packages/docs/content/v4/index.mdx
packages/zod/src/v4/classic/schemas.ts
packages/zod/src/v4/classic/tests/to-json-schema.test.ts
packages/zod/src/v4/core/schemas.ts
packages/zod/src/v4/core/to-json-schema.ts
play.ts

- **Implement OpenAPI-friendly JSON Schema for File schemas**
- **Fix unrepresentable tests**

Implement OpenAPI-friendly JSON Schema for File schemas

---

packages/docs/components/ecosystem.tsx

Ecosystem: Add Express Zod API

---

packages/docs/components/ecosystem-v3.tsx
packages/docs/components/ecosystem.tsx

Hey! Author or [regle](https://github.com/victorgarciaesgi/regle) here. 
It's just a quick wording fix because I noticed I've put the wrong names and link in the ecosystem docs! 
Thanks 👍

docs: updated name and link of `regle` library

---

packages/zod/src/v4/classic/tests/to-json-schema.test.ts
packages/zod/src/v4/core/checks.ts

Adds an extra regex check marker to includes when `position` isa added

v4(toJSONSchema): Add `includes` position check

---

packages/docs/components/ecosystem.tsx

Starting v4.0.0 it supports Zod 4.

Add Zod Sockets to Ecosystem

---

packages/bench/error-handling.ts
packages/bench/object.ts
packages/tsc/generate.ts

remove unused import & imported multiple times

refactor: remove unused import & imported multiple times

---

packages/zod/src/v4/core/schemas.ts

change if in else to else if for better readability

refactor: change if in else to else if

---

package.json
pnpm-lock.yaml

remove deprecated @types/chalk
- <https://www.npmjs.com/package/@types/chalk>

chore: remove deprecated @types/chalk

---

packages/docs/content/api.mdx
packages/docs/content/error-customization.mdx
packages/docs/content/v4/changelog.mdx
packages/zod/src/v4/classic/schemas.ts
packages/zod/tsconfig.json
play.ts

- **Improve changelog**
- **Closes #4854**

improve changelog

---

packages/zod/src/v4/classic/tests/catch.test.ts
packages/zod/src/v4/core/schemas.ts
play.ts

Closes https://github.com/colinhacks/zod/issues/4851

Unwiden catch input type

---

packages/docs/content/error-customization.mdx
packages/zod/src/v4/locales/index.ts
packages/zod/src/v4/locales/is.ts

Hi, my colleagues from Iceland have provided a translation of the errors into Icelandic.

feat: Icelandic translation

---

packages/docs/components/ecosystem.tsx

You could see document of valype at https://valype.dev/what-is-valype

docs: add valype to xToZodConverts

---

packages/docs/content/index.mdx

I don't think this is required now?

Remove moduleResolution callout

---

packages/zod/src/v4/classic/tests/literal.test.ts
packages/zod/src/v4/classic/tests/template-literal.test.ts
packages/zod/src/v4/core/schemas.ts

fix: escapes decimal place in `z.literal`

---

packages/docs/components/ecosystem.tsx

This PR adds upfetch to the ecosystem docs

docs(ecosystem): add upfetch

---

packages/docs/content/v4/index.mdx

fix zod version in content/v4/index
Close #5282

docs(content/v4/index): fix zod version
